import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {Store} from '../server/store';
import {createApp,initialProfile} from '../server/app';
import {defaultDesign,themes} from '../src/domain';
import {OpenAIProviders,compileBrief,providerError} from '../server/providers';
async function harness(options:any={}){const store=new Store(await mkdtemp(join(tmpdir(),'srez-test-')));const app=createApp({store,publicDir:resolve('public'),...options});const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',()=>r()));const port=(server.address() as any).port;const request=async(path:string,body?:any,key='key1')=>{const r=await fetch('http://127.0.0.1:'+port+'/api'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});return{status:r.status,body:await r.json()};};const close=async()=>{await new Promise<void>(r=>server.close(()=>r()));store.close();};return{store,request,close,port};}
const input={brandId:'kvartal',prompt:'Оранжевый фон и снеки справа',referenceAssetIds:[],brandVersion:1,draftRevision:0,count:1,quality:'medium',format:'full',strictness:'strict'};
async function wait(request:any,id:string){for(let i=0;i<200;i++){const r=await request('/jobs/'+id);if(['ready','failed','cancelled','interrupted'].includes(r.body.status))return r.body;await new Promise(r=>setTimeout(r,10));}throw new Error('job timeout');}
test('no key: editor works, no fake generation success',async()=>{const h=await harness();try{assert.equal((await h.request('/status')).body.connected,false);assert.equal((await h.request('/coupons/CP-104/generations',input)).status,503);assert.equal(h.store.all('job').length,0);const save=await h.request('/coupons/CP-104/design',{design:defaultDesign,expectedRevision:0});assert.equal(save.status,200);assert.equal(save.body.revision,1);assert.equal((await h.request('/coupons/CP-104/design',{design:defaultDesign,expectedRevision:0})).status,409);assert.equal((await h.request('/coupons/CP-104/design',{design:{...defaultDesign,discount:100},expectedRevision:1})).status,400);}finally{await h.close();}});
test('generation idempotency, native conditions unchanged, persistent asset, edit target',async()=>{let calls=0;const received:any[]=[];const bytes=await readFile('public/assets/kvartal-right.png');const h=await harness({images:{generate:async(prompt:any,assets:any)=>{calls++;received.push({prompt,assets});return{bytes};}}});try{const a=await h.request('/coupons/CP-104/generations',input);const b=await h.request('/coupons/CP-104/generations',input);assert.equal(a.status,202);assert.equal(a.body.jobId,b.body.jobId);const result=await wait(h.request,a.body.jobId);assert.equal(result.status,'ready');assert.equal(calls,1);assert.equal((await h.request('/coupons/CP-104/generations',{...input,prompt:'Другой запрос'})).status,409);const variant=result.results[0];assert.ok(variant.url.startsWith('/uploads/'));assert.ok((await readFile(h.store.get('asset',variant.assetId).path)).length>100);assert.match(received[0].prompt,/NO letters, logo, discount/);const edit=await h.request('/coupons/CP-104/variants/'+variant.id+'/edits',{...input,prompt:'Сделай фон темнее'},'edit');const edited=await wait(h.request,edit.body.jobId);assert.equal(edited.status,'ready');assert.equal(edited.results[0].parentVariantId,variant.id);assert.equal(received[1].assets[0].id,variant.assetId);assert.equal(received[1].assets[0].role,'edit target');assert.equal(h.store.get('coupon','CP-104').design,null);}finally{await h.close();}});
test('cross-brand rejection before provider call; bad variants rejected',async()=>{const h=await harness({images:{generate:()=>{throw new Error('must not run');}}});try{const r=await h.request('/coupons/CP-104/generations',{...input,referenceAssetIds:['example-copper-0']});assert.equal(r.status,403);assert.equal(h.store.all('job').length,0);assert.equal((await h.request('/coupons/CP-104/variants/unknown/edits',input)).status,403);const save=await h.request('/coupons/CP-104/design',{design:{...defaultDesign,asset:'/assets/copper.png'},expectedRevision:0});assert.equal(save.status,400);}finally{await h.close();}});
test('partial results and cancellation are honest',async()=>{let count=0;const bytes=await readFile('public/assets/kvartal-air.png');const h=await harness({images:{generate:async()=>{if(++count===2)throw{status:429};return{bytes};}}});try{const r=await h.request('/coupons/X/generations',{...input,count:3});const j=await wait(h.request,r.body.jobId);assert.equal(j.status,'ready');assert.equal(j.results.length,2);assert.equal(j.errors.length,1);assert.equal(count,3);}finally{await h.close();}let resolveCall:any;const h2=await harness({images:{generate:()=>new Promise(r=>{resolveCall=r;})}});try{const r=await h2.request('/coupons/X/generations',input);for(let i=0;i<40&&!resolveCall;i++)await new Promise(r=>setTimeout(r,5));await h2.request('/jobs/'+r.body.jobId+'/cancel',{});resolveCall({bytes});const j=await wait(h2.request,r.body.jobId);assert.equal(j.status,'cancelled');assert.equal(h2.store.all('variant').length,0);}finally{await h2.close();}});
test('interrupted work restored on server restart without rerun',async()=>{const store=new Store(await mkdtemp(join(tmpdir(),'srez-restart-')));store.put('job',{id:'old',brandId:'kvartal',status:'generating',input,count:1});createApp({store});assert.equal(store.get('job','old').status,'interrupted');store.close();});
test('brand analysis uses own references and saves confirmed version',async()=>{const h=await harness({analysis:{analyze:async(p:any,a:any[])=>({...p,status:'draft',sourceAssets:a.map(x=>x.id)})}});try{const r=await h.request('/brands/kvartal/analyses',{...input,referenceAssetIds:['example-kvartal-0']});const j=await wait(h.request,r.body.jobId);assert.equal(j.status,'ready');assert.equal(j.profile.status,'draft');const v=await h.request('/brands/kvartal/versions',j.profile);assert.equal(v.body.version,2);assert.equal(v.body.status,'confirmed');assert.equal((await h.request('/brands/kvartal')).body.version,2);}finally{await h.close();}});
test('upload rejects active SVG and enforces file ownership',async()=>{const h=await harness();try{const body=new FormData();body.append('files',new Blob(['<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>'],{type:'image/svg+xml'}),'unsafe.svg');const r=await fetch(`http://127.0.0.1:${h.port}/api/brands/kvartal/assets`,{method:'POST',body});assert.equal(r.status,400);const img=new FormData();img.append('files',new Blob([new Uint8Array(await readFile('public/assets/kvartal-air.png'))],{type:'image/png'}),'test.png');const a=await fetch(`http://127.0.0.1:${h.port}/api/brands/kvartal/assets`,{method:'POST',body:img});assert.equal(a.status,201);const b=await a.json() as any;const cross=await h.request('/coupons/x/generations',{...input,brandId:'copper',referenceAssetIds:[b.assets[0].id]});assert.equal(cross.status,403);}finally{await h.close();}});
test('SDK adapter uses actual image API generate/edit with maxRetries zero',async()=>{const p=new OpenAIProviders('test-only-not-a-secret','gpt-image-2.5-sunburst','gpt-4.1');const operations:any[]=[];(p.client.images as any).generate=async(body:any)=>{operations.push(body);return{data:[{b64_json:Buffer.from('test').toString('base64')}]};};(p.client.images as any).edit=async(body:any)=>{operations.push(body);return{data:[{b64_json:Buffer.from('test-edit').toString('base64')}]};};assert.equal((await p.generate('test',[],'low',new AbortController().signal)).bytes.toString(),'test');await p.generate('edit',[{id:'a',brandId:'kvartal',path:resolve('public/assets/kvartal-right.png'),url:'',name:'x.png',mime:'image/png',role:'edit target',source:'example'}],'medium',new AbortController().signal);assert.ok(operations[1].image.length===1);assert.equal(operations[1].model,'gpt-image-2.5-sunburst');assert.equal(p.client.maxRetries,0);assert.equal(providerError({status:401}).code,'auth');assert.equal(providerError({name:'APIConnectionTimeoutError'}).code,'uncertain');});
