import express from 'express';
import multer from 'multer';
import sharp from 'sharp';
import {randomUUID,createHash} from 'node:crypto';
import {resolve,join,extname} from 'node:path';
import {writeFile,readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {z} from 'zod';
import {designSchema} from '../src/designSchema';
import {Store} from './store';
import type {BrandProfile} from '../src/brandSchema';
import {themes,defaultDesign} from '../src/domain';
import {profileSchema,compileBrief,providerError,type BrandAnalysisProvider,type ImageGenerationProvider,type Asset} from './providers';
const id=z.string().regex(/^[\w-]{1,100}$/);
const genInput=z.object({brandId:id,prompt:z.string().min(3).max(4000),referenceAssetIds:z.array(id).max(10).default([]),productAssetId:id.optional(),brandVersion:z.number().int().positive(),draftRevision:z.number().int().nonnegative(),count:z.union([z.literal(1),z.literal(3)]),quality:z.enum(['low','medium','high']).default('medium'),format:z.enum(['full','list','banner']).default('full'),strictness:z.enum(['strict','creative']).default('strict')}).strict();

import {initialProfile} from '../src/initialBrandProfile';
export {initialProfile} from '../src/initialBrandProfile';

export function createApp(options:{store:Store;analysis?:BrandAnalysisProvider;images?:ImageGenerationProvider;models?:{image:string;analysis:string};maxJobs?:number;concurrent?:number;publicDir?:string}){
 const {store}=options;const app=express();const running=new Map<string,AbortController>();const publicDir=options.publicDir||resolve('public');app.disable('x-powered-by');app.use(express.json({limit:'2mb'}));
 app.use('/api',(req,res,next)=>{const origin=req.headers.origin;if(origin&&!/^http:\/\/(127\.0\.0\.1|localhost):(5178|4178)$/.test(origin))return res.status(403).json({error:'Запрос с другого сайта запрещён'});res.setHeader('Cache-Control','no-store');next();});
 app.use('/uploads',express.static(join(store.dir,'assets'),{setHeaders:res=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'none'; sandbox");}}));
 for(const t of themes){if(!store.get('brand',t.id)){const profile=initialProfile(t);store.put('brand',{id:t.id,brandId:t.id,name:t.name,version:1});store.put('version',{...profile,id:`${t.id}-v1`});}}
 for(const t of themes){const paths=t.id==='kvartal'?['/assets/kvartal-right.png','/assets/kvartal-air.png','/assets/kvartal-scene.png']:[t.asset];const sourceIds:string[]=[];for(const [i,url] of paths.entries()){const aid='example-'+t.id+'-'+i;if(!existsSync(resolve(publicDir,'.'+url)))continue;sourceIds.push(aid);if(!store.get('asset',aid))store.put('asset',{id:aid,brandId:t.id,name:'Пример · '+['Товар справа','Больше воздуха','Предметная сцена'][i],mime:'image/png',path:resolve(publicDir,'.'+url),url,role:'style',source:'example'});}const p=store.get('version',t.id+'-v1');if(p&&!p.sourceAssets.length&&sourceIds.length)store.put('version',{...p,sourceAssets:sourceIds});}
 for(const j of store.all('job'))if(['queued','preparing','generating','composing'].includes(j.status))store.put('job',{...j,status:'interrupted',error:{code:'interrupted',message:'Сервер перезапущен. Работа не повторялась. Можно начать новый запрос вручную.'},finishedAt:new Date().toISOString()});
 const getBrand=(brandId:string)=>{const b=store.get('brand',brandId);if(!b)throw Object.assign(new Error('Сеть не найдена'),{status:404});return b;};
 const checkedAssets=(brandId:string,ids:string[])=>ids.map(assetId=>{const a=store.get<Asset>('asset',assetId);if(!a||a.brandId!==brandId)throw Object.assign(new Error('Материал не принадлежит выбранной сети'),{status:403});return a;});
 app.get('/api/status',(_req,res)=>res.json({connected:!!options.images,analysisConnected:!!options.analysis,models:options.models,limits:{daily:options.maxJobs||20,concurrent:options.concurrent||2,fileMB:10},mode:options.images?'live':'example'}));
 app.get('/api/brands',(req,res)=>res.json(store.all('brand')));
 app.get('/api/brands/:brandId',(req,res)=>{const b=getBrand(req.params.brandId);res.json({...b,profile:store.get('version',`${b.id}-v${b.version}`),versions:store.all('version',b.id),assets:store.all('asset',b.id)});});
 const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024,files:10}});
 async function saveImage(bytes:Buffer,brandId:string,name:string,role:string,source:string,extra={}){const meta=await sharp(bytes,{limitInputPixels:25e6}).metadata();if(!meta.width||!meta.height)throw new Error('Пустое изображение');const safe=await sharp(bytes,{limitInputPixels:25e6}).rotate().resize({width:2048,height:2048,fit:'inside',withoutEnlargement:true}).png().toBuffer();const assetId=randomUUID();const path=join(store.dir,'assets',assetId+'.png');await writeFile(path,safe);return store.put('asset',{id:assetId,brandId,name:name.replace(/[^\p{L}\p{N} ._-]/gu,'').slice(0,100)||'Изображение',mime:'image/png',path,url:`/uploads/${assetId}.png`,role,source,...extra});}
 app.post('/api/brands/:brandId/assets',upload.array('files',10),async(req,res)=>{const brandId=String(req.params.brandId);getBrand(brandId);const files=req.files as Express.Multer.File[];if(!files?.length)return res.status(400).json({error:'Выберите файл'});const result=[];for(const file of files){const ext=extname(file.originalname).toLowerCase();if(ext==='.svg'){const svg=file.buffer.toString();if(/<script|<foreignObject|on\w+\s*=|href\s*=|url\s*\(|<!ENTITY|<!DOCTYPE/i.test(svg))throw Object.assign(new Error('SVG содержит активное или внешнее содержимое'),{status:400});result.push(await saveImage(file.buffer,brandId,file.originalname,req.body.role||'style','upload'));}else if(['.png','.jpg','.jpeg','.webp'].includes(ext)){result.push(await saveImage(file.buffer,brandId,file.originalname,req.body.role||'style','upload'));}else if(ext==='.pdf'){if(file.buffer.subarray(0,5).toString()!=='%PDF-')throw new Error('Некорректный PDF');const parentId=randomUUID();const path=join(store.dir,'assets',parentId+'.pdf');await writeFile(path,file.buffer);const pdfAsset=store.put('asset',{id:parentId,brandId,name:file.originalname,mime:'application/pdf',path,url:`/uploads/${parentId}.pdf`,role:'brandbook',source:'upload'});result.push(pdfAsset);const {getDocument}=await import('pdfjs-dist/legacy/build/pdf.mjs');const {createCanvas}=await import('@napi-rs/canvas');const doc=await getDocument({data:new Uint8Array(file.buffer),useSystemFonts:true,isEvalSupported:false}).promise;const pages=String(req.body.pages||'1,2,3').split(',').map(Number).filter(n=>n>=1&&n<=doc.numPages).slice(0,5);for(const n of pages){const page=await doc.getPage(n),viewport=page.getViewport({scale:1.3}),canvas=createCanvas(viewport.width,viewport.height);await page.render({canvasContext:canvas.getContext('2d') as any,viewport,canvas:canvas as any}).promise;result.push(await saveImage(canvas.toBuffer('image/png'),brandId,`${file.originalname} · стр. ${n}`,'style','pdf',{parentId,page:n}));}await doc.destroy();}else if(['.woff','.woff2','.ttf','.otf'].includes(ext)){const sig=file.buffer.subarray(0,4).toString('hex');if(!['774f4646','774f4632','00010000','4f54544f'].includes(sig))throw new Error('Некорректный файл шрифта');const aid=randomUUID(),path=join(store.dir,'assets',aid+ext);await writeFile(path,file.buffer);result.push(store.put('asset',{id:aid,brandId,name:file.originalname,mime:'font/'+ext.slice(1),path,url:`/uploads/${aid}${ext}`,role:'font',source:'upload'}));}else throw Object.assign(new Error('Поддерживаются PNG, JPG, WebP, безопасный SVG, PDF и шрифты'),{status:400});}res.status(201).json({assets:result.map(({path,...a})=>a)});});
 app.post('/api/brands/:brandId/versions',(req,res)=>{const b=getBrand(req.params.brandId);const profile=profileSchema.parse(req.body);if(profile.brandId!==b.id)throw Object.assign(new Error('Профиль принадлежит другой сети'),{status:403});checkedAssets(b.id,[...profile.sourceAssets,...profile.provenance.flatMap(p=>p.sourceAssetIds),...(profile.logoAssetId?[profile.logoAssetId]:[]),...[profile.typography.display.assetId,profile.typography.body.assetId].filter((x):x is string=>!!x)]);const saved=store.transaction(()=>{const version=b.version+1;store.put('brand',{...b,version,name:profile.name});return store.put('version',{...profile,id:`${b.id}-v${version}`,version,status:'confirmed'});});res.status(201).json(saved);});
 app.get('/api/coupons/:couponId',(req,res)=>{const c=store.get('coupon',req.params.couponId);res.json(c||{id:req.params.couponId,brandId:'kvartal',revision:0,design:null,variants:[]});});
 app.post('/api/coupons/:couponId/design',(req,res)=>{const body=z.object({design:designSchema,expectedRevision:z.number().int().min(0)}).parse(req.body);getBrand(body.design.brandId);const c=store.get('coupon',req.params.couponId)||{id:req.params.couponId,brandId:body.design.brandId,revision:0,variants:[]};if(c.revision!==body.expectedRevision)return res.status(409).json({error:'Черновик изменился в другом окне. Обновите его перед сохранением.',revision:c.revision});if(body.design.asset.startsWith('/uploads/')){const a=store.all<Asset>('asset').find(a=>a.url===body.design.asset);if(!a||a.brandId!==body.design.brandId)return res.status(403).json({error:'Чужой материал'});}else if(!(body.design.brandId==='kvartal'?['/assets/kvartal-right.png','/assets/kvartal-air.png','/assets/kvartal-scene.png']:[themes.find(t=>t.id===body.design.brandId)?.asset]).includes(body.design.asset))return res.status(400).json({error:'Недопустимый путь изображения'});if(body.design.logo){const logo=store.all<Asset>('asset',body.design.brandId).find(a=>a.url===body.design.logo&&a.mime.startsWith('image/'));if(!logo)return res.status(403).json({error:'Логотип не принадлежит сети'});}if(body.design.brandTokens?.fontUrl){const font=store.all<Asset>('asset',body.design.brandId).find(a=>a.url===body.design.brandTokens?.fontUrl&&a.mime.startsWith('font/'));if(!font)return res.status(403).json({error:'Шрифт не принадлежит сети'});}if(body.design.variantId){const v=store.get('variant',body.design.variantId);if(!v||v.couponId!==c.id||v.brandId!==body.design.brandId)return res.status(403).json({error:'Чужой вариант'});}const next={...c,brandId:body.design.brandId,revision:c.revision+1,design:{...body.design,revision:c.revision+1}};store.transaction(()=>{store.put('coupon',next);store.put('design-version',{id:`${c.id}-${next.revision}`,brandId:next.brandId,couponId:c.id,...next.design});});res.json(next);});
 async function run(jobId:string){const j=store.get('job',jobId);if(!j||j.status!=='queued')return;const controller=new AbortController();running.set(jobId,controller);const update=(part:any)=>{const old=store.get('job',jobId);if(old.status==='cancelled')return old;return store.put('job',{...old,...part,updatedAt:new Date().toISOString()});};try{update({status:'preparing'});const profile=store.get('version',`${j.brandId}-v${j.input.brandVersion}`);const references=checkedAssets(j.brandId,j.input.referenceAssetIds||[]);if(j.type==='analysis'){update({status:'generating'});const result=await options.analysis!.analyze(profile,references,controller.signal);if(result.brandId!==j.brandId)throw new Error('Сеть в ответе не совпадает');checkedAssets(j.brandId,[...result.sourceAssets,...result.provenance.flatMap((p:any)=>p.sourceAssetIds)]);update({status:'ready',profile:{...result,status:'draft'},finishedAt:new Date().toISOString()});}else{const results:any[]=[];const errors:any[]=[];for(let i=0;i<j.input.count;i++){if(controller.signal.aborted)break;update({status:'generating',stage:`Вариант ${i+1} из ${j.input.count}`});try{const target=j.parentVariantId?store.get('variant',j.parentVariantId):null;const targetAsset=target?checkedAssets(j.brandId,[target.assetId])[0]:null;const assets=[...(targetAsset?[{...targetAsset,role:'edit target'}]:[]),...(j.input.productAssetId?checkedAssets(j.brandId,[j.input.productAssetId]).map(a=>({...a,role:'product reference'})):[]),...references];const prompt=compileBrief(profile,j.input.prompt,j.input.format,i,j.input.strictness,assets,!!target);const out=await options.images!.generate(prompt,assets,j.input.quality,controller.signal);if(controller.signal.aborted)break;update({status:'composing'});const asset=await saveImage(out.bytes,j.brandId,`Вариант ${i+1}`,'generated','live');const variant=store.put('variant',{id:randomUUID(),brandId:j.brandId,couponId:j.couponId,assetId:asset.id,url:asset.url,parentVariantId:j.parentVariantId||null,brandVersion:j.input.brandVersion,draftRevision:j.input.draftRevision,jobId,usage:out.usage});results.push(variant);update({results:[...results]});}catch(e){errors.push(providerError(e));update({errors:[...errors]});if(controller.signal.aborted)break;}}if(!controller.signal.aborted)update({status:results.length?'ready':'failed',results,errors,error:results.length?null:errors[0],finishedAt:new Date().toISOString()});}}catch(e){update({status:'failed',error:providerError(e),finishedAt:new Date().toISOString()});}finally{running.delete(jobId);}}
 function enqueue(req:express.Request,res:express.Response,type:'analysis'|'generation',parentVariantId?:string){const input=genInput.parse(req.body);const b=getBrand(input.brandId);if(type==='analysis'&&req.params.brandId!==b.id)return res.status(403).json({error:'Сеть не совпадает'});const p=store.get('version',`${b.id}-v${input.brandVersion}`);if(!p)return res.status(400).json({error:'Версия стиля не найдена'});checkedAssets(b.id,[...input.referenceAssetIds,...(input.productAssetId?[input.productAssetId]:[])]);const couponId=type==='generation'?String(req.params.couponId):null;const c=couponId?store.get('coupon',couponId):null;if(c&&c.brandId!==b.id)return res.status(403).json({error:'Купон принадлежит другой сети'});if(parentVariantId){const v=store.get('variant',parentVariantId);if(!v||v.brandId!==b.id||v.couponId!==couponId)return res.status(403).json({error:'Вариант принадлежит другому купону'});}const key=req.header('Idempotency-Key');if(!key||key.length>100)return res.status(400).json({error:'Требуется ключ идемпотентности'});const scope=`${b.id}:${type}:${couponId||b.id}:${parentVariantId||''}`,hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');const prior=store.db.prepare('SELECT * FROM idempotency WHERE scope=? AND key=?').get(scope,key) as any;if(prior){if(prior.hash!==hash)return res.status(409).json({error:'Ключ уже использован с другим запросом'});return res.status(202).json({jobId:prior.job});}if(!(type==='analysis'?options.analysis:options.images))return res.status(503).json({error:'Подключите генерацию в настройках. Запрос сохранён в редакторе.',code:'not_configured'});if(type==='analysis'&&!input.referenceAssetIds.length)return res.status(400).json({error:'Загрузите хотя бы один материал'});const jobs=store.all('job',b.id);if(jobs.filter(j=>['queued','preparing','generating','composing'].includes(j.status)).length>=(options.concurrent||2))return res.status(429).json({error:'Дождитесь текущей работы'});if(jobs.filter(j=>j.createdAt.slice(0,10)===new Date().toISOString().slice(0,10)).reduce((s,j)=>s+(j.input.count||1),0)+input.count>(options.maxJobs||20))return res.status(429).json({error:'Дневной лимит запросов сети исчерпан'});const jobId=randomUUID();store.transaction(()=>{if(couponId&&!c)store.put('coupon',{id:couponId,brandId:b.id,revision:0,design:null,variants:[]});store.put('job',{id:jobId,brandId:b.id,couponId,type,parentVariantId,input,compiledBriefVersion:1,mode:'live',provider:'openai',model:type==='analysis'?options.models?.analysis:options.models?.image,status:'queued',results:[],createdAt:new Date().toISOString()});store.db.prepare('INSERT INTO idempotency VALUES(?,?,?,?)').run(scope,key,hash,jobId);});res.status(202).json({jobId});setImmediate(()=>void run(jobId));}
 app.post('/api/brands/:brandId/analyses',(req,res)=>enqueue(req,res,'analysis'));
 app.post('/api/coupons/:couponId/generations',(req,res)=>enqueue(req,res,'generation'));
 app.post('/api/coupons/:couponId/variants/:variantId/edits',(req,res)=>enqueue(req,res,'generation',String(req.params.variantId)));
 app.get('/api/jobs/:jobId',(req,res)=>{const j=store.get('job',req.params.jobId);if(!j)return res.status(404).json({error:'Работа не найдена'});res.json(j);});
 app.get('/api/coupons/:couponId/variants',(req,res)=>{const couponId=String(req.params.couponId);const c=store.get('coupon',couponId);const brandId=c?.brandId||'kvartal';for(const a of store.all<Asset>('asset',brandId).filter(a=>a.source==='example')){const vid='example-'+couponId+'-'+a.id;if(!store.get('variant',vid))store.put('variant',{id:vid,brandId,couponId,assetId:a.id,url:a.url,example:true,parentVariantId:null,brandVersion:1,draftRevision:0});}res.json(store.all('variant',brandId).filter(v=>v.couponId===couponId));});
 app.post('/api/jobs/:jobId/cancel',(req,res)=>{const j=store.get('job',req.params.jobId);if(!j)return res.status(404).json({error:'Работа не найдена'});if(['ready','failed','cancelled','interrupted'].includes(j.status))return res.json(j);running.get(j.id)?.abort();res.json(store.put('job',{...j,status:'cancelled',finishedAt:new Date().toISOString(),error:{message:'Ожидание отменено. Начатая работа у провайдера могла продолжиться; результат не применяется.'}}));});
 app.post('/api/brands/:brandId/style-examples',async(req,res)=>{getBrand(req.params.brandId);const v=store.get('variant',req.body.variantId);if(!v||v.brandId!==req.params.brandId)return res.status(403).json({error:'Чужой вариант'});const a=checkedAssets(v.brandId,[v.assetId])[0];res.status(201).json(await saveImage(await readFile(a.path),a.brandId,'Одобренный пример','style','approved'));});
 app.use(express.static(publicDir));
 app.use((error:any,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(error instanceof z.ZodError)return res.status(400).json({error:'Некорректные поля',details:error.issues.map(i=>`${i.path.join('.')}: ${i.message}`)});if(error.code==='LIMIT_FILE_SIZE')return res.status(413).json({error:'Файл больше 10 МБ'});res.status(error.status||400).json({error:error.message||'Не удалось обработать запрос'});});
 return app;
}
