import {test,expect} from '@playwright/test';
test('filters, segment, margin, persistence, design, redemption, screenshots',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/overview');await expect(page.getByRole('heading',{name:'Динамика продаж'})).toBeVisible({timeout:60000});await page.screenshot({path:'screenshots/01-overview.png'});
 const first=await page.locator('.kpi').first().innerText();await page.getByRole('button',{name:'Все 12 магазинов'}).click();await page.getByRole('button',{name:'14 дней',exact:true}).click();await page.getByRole('button',{name:'Готово',exact:true}).click();await expect(page.locator('.kpi').first()).not.toHaveText(first);const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Экспорт',exact:true}).click();await expect((await downloaded).suggestedFilename()).toContain('.csv');
 await page.goto('/segments/weekend');await expect(page.getByRole('heading',{name:'Профиль покупателя'})).toBeVisible();await page.screenshot({path:'screenshots/02-customers.png'});const audience=await page.locator('.segment-totals').innerText();await page.getByLabel('Значение условия 1',{exact:true}).fill('8');await expect(page.locator('.segment-totals')).not.toHaveText(audience);await page.getByLabel('Значение условия 1',{exact:true}).fill('4');await page.locator('.receipt-row').first().click();await expect(page.getByRole('dialog')).toContainText('Итого');await page.getByRole('button',{name:'Закрыть',exact:true}).click();
 await page.goto('/campaigns');await page.screenshot({path:'screenshots/03-campaigns.png'});await page.getByRole('button',{name:'Дизайн',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Студия купонов'})).toBeVisible();await page.screenshot({path:'screenshots/04-coupon-studio.png'});await page.getByRole('button',{name:'Свойства',exact:true}).click();await page.getByLabel('Заголовок',{exact:true}).fill('Вкусный повод вернуться');await page.getByRole('button',{name:'Сохранить',exact:true}).click();await expect(page.locator('.toast')).toContainText('Дизайн сохранён');await page.reload();await expect(page.locator('.canvas-coupon')).toContainText('Вкусный повод вернуться');
 await page.goto('/campaigns/CP-104');await page.getByRole('button',{name:'2 Предложение'}).click();await page.getByLabel('Скидка',{exact:true}).fill('25');await expect(page.locator('.error-box')).toContainText('ниже минимальной');await page.getByLabel('Скидка',{exact:true}).fill('10');await page.getByRole('button',{name:'5 Проверка'}).click();await page.getByRole('button',{name:'Сохранить и запустить демо',exact:true}).click();await page.getByRole('button',{name:'16 сентября · активировать'}).click();await page.getByRole('button',{name:'Демо-касса',exact:true}).click();await page.getByRole('button',{name:'Применить купон',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Купон применён');await page.getByRole('button',{name:'Применить купон',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Купон уже использован');await page.getByRole('button',{name:'Закрыть',exact:true}).click();expect(errors).toEqual([]);
});
test('1280, 1440, 768 and 390 layouts, reduced motion',async({page})=>{for(const [width,height] of [[1600,1000],[1440,900],[1280,800],[768,1000],[390,844]]){await page.setViewportSize({width,height});for(const [path,name] of [['/overview','overview'],['/segments/weekend','customers'],['/campaigns','campaigns'],['/coupons/CP-104/design','studio']]){await page.goto(path);await expect(page.locator('.loading')).toHaveCount(0,{timeout:60000});await expect(page.locator('h1').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),path+' '+width).toBe(true);if(width===1280||width===390)await page.screenshot({path:`screenshots/${name}-${width}.png`,fullPage:true});}}await page.goto('/settings');await page.getByLabel('Интенсивность анимаций').selectOption('minimal');await expect(page.locator('.app')).toHaveClass(/reduced/);await page.getByRole('link',{name:'Обзор',exact:true}).click();await expect(page.getByRole('heading',{name:'Динамика продаж'})).toBeVisible();});
