import {z} from 'zod/v3';
import {addDays,dayStart,DAY,type Dataset,type Filters,type Campaign} from './domain';
import {engagementReport} from './engagement';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),metric=z.object({count:z.number().int().nonnegative(),customers:z.number().int().nonnegative()}).strict();
export const assistantInputSchema=z.object({question:z.string().trim().min(1).max(4000),history:z.array(z.object({question:z.string().max(4000),answer:z.string().max(8000)}).strict()).max(6),snapshot:z.object({network:z.string().max(100),source:z.string().max(200),period:z.object({from:date,to:date,previousFrom:date,previousTo:date}),current:metric,previous:metric,daily:z.array(metric.extend({date})).max(366),stores:z.array(metric.extend({id:z.string(),name:z.string()})).max(100),campaigns:z.array(z.object({name:z.string(),status:z.string(),assigned:z.number().int(),redeemed:z.number().int()})).max(20),limitations:z.array(z.string().max(300)).max(12)}).strict()}).strict();
export type AssistantInput=z.infer<typeof assistantInputSchema>;
export const assistantOutputSchema=z.object({answer:z.string(),section:z.enum(['customers','campaigns','results','assistant'])}).strict();
export type AssistantOutput=z.infer<typeof assistantOutputSchema>;
export function assistantContext(data:Dataset,filters:Filters,network:string,campaigns:Campaign[],_legacy?:unknown){
 const length=Math.round((dayStart(filters.to)-dayStart(filters.from))/DAY)+1;if(length<1||length>366)throw Error('Выберите период от 1 до 366 дней.');const r=engagementReport(data,filters),metric=({count,customers}:{count:number;customers:number})=>({count,customers});
 return {network:network.slice(0,100),source:data.label.slice(0,200),period:{from:filters.from,to:filters.to,previousFrom:addDays(filters.from,-length),previousTo:addDays(filters.from,-1)},current:metric(r),previous:metric(r.previous),daily:r.daily.map(d=>({date:d.date,...metric(d)})),stores:r.stores.filter(s=>!filters.stores.length||filters.stores.includes(s.id)).map(s=>({id:s.id,name:s.name,...metric(s)})),campaigns:campaigns.slice(0,20).map(c=>({name:c.name,status:c.status,assigned:c.assignments.filter(a=>a.group==='offer').length,redeemed:c.assignments.filter(a=>a.used).length})),limitations:['Финансовые данные не передаются и не анализируются.','Это локальный снимок; прямая синхронизация с базой не настроена.','Пол, возраст и персональные записи покупателей не передаются модели.','Подбор аудитории — по заданным полям; отсутствующие признаки не угадываются.','Применение купона и повторный визит не доказывают причинный эффект.']};
}
