import {stores,report,audience,baseSegment,matches,economy,defaultOffer,num,money,compact,addDays,categories,customerStats,type Dataset,type Filters} from './domain';
export function answerQuestion(question:string,data:Dataset,filters:Filters){const q=question.toLowerCase();const days=q.match(/(?:последн\S*|за)\s+(\d+)\s+д/);const f={...filters,...(days?{from:addDays('2026-09-14',-Math.min(120,Number(days[1]))),to:'2026-09-13'}:{})};const named=stores.filter(s=>q.includes(s.name.toLowerCase().slice(0,Math.max(4,s.name.length-2))));if(named.length)f.stores=named.map(s=>s.id);if(/снек|чипс|орех/.test(q))f.category=2;if(/безалког|лимонад/.test(q))f.category=3;const r=report(data,f),context=`${f.from} — ${f.to} · ${f.stores.length?f.stores.join(', '):'12 магазинов'} · ${f.category===undefined?'все категории':categories[f.category]} · локальный анализ`;let answer='',link='/sales?'+new URLSearchParams({from:f.from,to:f.to,stores:f.stores.join(','),...(f.category===undefined?{}:{category:String(f.category)})});
 if(/созда|подготов.*(?:предлож|сегмент)|собер/.test(q)){answer=`Подготовлю предложение по выходным покупкам. В поведенческом сегменте ${num(audience(data,baseSegment).behavior.length)} покупателей, доступны ${num(audience(data,baseSegment).eligible.length)}. Проверьте условия перед запуском.`;link='/segments/weekend';}
 else if(/марж|скидк/.test(q)){const percent=Number(q.match(/(\d+)\s*%/)?.[1]||10);const p=data.products.find(p=>p.id==='P003')!,e=economy(p,{...defaultOffer,value:percent});answer=`При скидке ${percent}% цена ${money(e.price,2)}, валовая прибыль ${e.profit===null?'неизвестна':money(e.profit,2)}, маржа ${e.margin===null?'не рассчитана':num(e.margin,2)+'%'}. ${e.margin!==null&&e.margin>=25?'Порог 25% соблюдён.':'Запуск блокируется: минимальная маржа 25%.'} Расчёт для ${p.name}, цена ${money(p.price)}, себестоимость ${p.cost===null?'неизвестна':money(p.cost)}.`;link='/campaigns/CP-104';}
 else if(/эксперимент|пилот|подтвержд|результат/.test(q)){answer='В эталонном пилоте CP-097 оценка после расходов +19 200 ₽. 95% интервал: от −820 до +39 180 ₽. Он включает ноль: положительный эффект пока не подтверждён. Это отдельный эталонный набор за 17.08–13.09.2026.';link='/experiments/CP-097';}
 else if(/исключ|уменьш.*аудитор|доступн.*меньше/.test(q)){const a=audience(data,baseSegment);answer=`Из ${num(a.behavior.length)} покупателей доступны ${num(a.eligible.length)}. ${a.excluded.map(e=>`${e.reason}: ${num(e.count)}`).join('; ')}. Исключения применяются последовательно и не складываются дважды.`;link='/segments/weekend';}
 else if(/давно|не приход|не покупа\S*\s+\d+\s+д/.test(q)){const n=Number(q.match(/(\d+)\s+д/)?.[1]||30);const count=data.customers.filter(c=>{const s=customerStats(c);return s.last!==null&&s.last>=n;}).length;answer=`${num(count)} покупателей не покупали ${n} дней или больше. Возраст последнего чека рассчитан на 14.09.2026. Покупатели без истории считаются отдельно.`;link=`/customers?intent=lost&days=${n}`;}
 else if(/выходн|пятниц|суббот/.test(q)){const a=audience(data,baseSegment);answer=`${num(a.behavior.length)} покупателей соответствуют сценарию: минимум 4 чека за 90 дней, от 60% в пятницу/субботу, покупка за 28 дней и отсутствие снеков за 60 дней. Для предложения доступны ${num(a.eligible.length)}.`;link='/segments/weekend';}
 else if(/не покуп.*(?:категор|снек|напит|лимонад)/.test(q)){const cat=f.category??2;const g={id:'g',logic:'AND' as const,children:[{id:'r',field:'category' as const,op:'not',value:cat,window:60}]};answer=`${num(data.customers.filter(c=>matches(c,g,data.start)).length)} покупателей не покупали категорию «${categories[cat]}» за 60 полных дней. Требуется достаточная история источника.`;link='/customers?intent=no-category&category='+cat;}
 else if(/почему|вклад|изменил/.test(q)){const rows=[...r.stores].sort((a,b)=>(b.revenue-b.previous.revenue)-(a.revenue-a.previous.revenue));answer=`Выручка изменилась на ${compact(r.revenue-r.previous.revenue)}. Наибольший наблюдаемый вклад: ${rows.slice(0,3).map(s=>`${s.name}: ${compact(s.revenue-s.previous.revenue)}`).join('; ')}. Это вклад в изменение, а не доказанная причина.`;}
 else if(/лучш|слаб|магазин|точк/.test(q)){const low=/слаб|худш|низ/.test(q);const metric=/прибыл/.test(q)?'profit':'revenue';const rows=[...r.stores].filter(s=>!f.stores.length||f.stores.includes(s.id)).sort((a,b)=>low?a[metric]-b[metric]:b[metric]-a[metric]);answer=`${low?'Меньше':'Больше'} всего ${metric==='profit'?'валовой прибыли':'выручки'}: ${rows.slice(0,3).map(s=>`${s.name} — ${compact(s[metric])}`).join('; ')}. Средние значения взвешены по количеству чеков.`;}
 else if(/топ|товар|категор|что покуп|снек|лимонад/.test(q)){answer=`Продажи выбранного ассортимента: ${compact(r.revenue)}, ${num(r.count)} чеков. Категории: ${[...r.categories].sort((a,b)=>b.revenue-a.revenue).slice(0,3).map(c=>`${c.name} — ${compact(c.revenue)}`).join('; ')}. После скидок и возвратов.`;}
 else if(/прибыл|себестоим/.test(q)){answer=`Валовая прибыль ${compact(r.profit)}. Покрытие себестоимости ${num(r.coverage*100,1)}%. ${r.coverage<1?'Это прибыль по известной части, полного итога нет.':'Все строки обеспечены себестоимостью.'} Без НДС, после скидок и возвратов.`;}
 else if(/выруч|продаж|оборот|доход/.test(q)){answer=`Выручка ${compact(r.revenue)}; предыдущий сопоставимый период ${compact(r.previous.revenue)}. Изменение ${r.previous.revenue?num((r.revenue/r.previous.revenue-1)*100,1)+'%':'не определено'}. ${num(r.count)} чеков продаж, средний чек ${money(r.average)}. Анонимные продажи включены.`;}
 else {answer='Этот вопрос пока не поддерживается. Могу сравнить выручку и прибыль, найти товары и магазины, объяснить аудиторию, рассчитать маржу и открыть результат пилота. Уточните, какой показатель и период вас интересует.';link='/assistant';}
 return{question,answer,link,context};}
