import {Play,Pause,ShoppingCart,Check} from 'lucide-react';
import {useState} from 'react';
import {useStore} from './store';
import {money,num,statusLabels,type Campaign} from './domain';
import {firstOfferTime} from './campaignFlow';
import {Button,Modal} from './ui';
export function CampaignLaunch({campaign:c,onCash}:{campaign:Campaign;onCash:()=>void}){
 const state=useStore(),[finish,setFinish]=useState(false),offer=c.snapshot?.offer||c.offer;
 const recipients=c.assignments.filter(a=>a.group==='offer'),events=state.events.filter(e=>e.campaignId===c.id);
 const at=firstOfferTime(offer),canOperate=state.settings.role!=='manager';
 function activate(){if(!at)return;useStore.setState({simulationDate:at});state.updateCampaign(c.id,{status:'active'},c.status==='paused'?'Демо возобновлено':'Демо запущено');state.notify('Купоны активны. Проверьте применение в демо-кассе.');}
 return <section className="panel simulation-panel campaign-launch"><div className="split"><div><span className={'badge '+c.status}>{statusLabels[c.status]}</span><h2>Запуск и проверка купона</h2><p>Назначения сохранены. Проверка проходит в демо-кассе; отправка покупателям появится после подключения приложения сети.</p></div></div><div className="launch-metrics"><div><small>Получателей</small><strong>{num(recipients.length)}</strong></div><div><small>Купонов применено</small><strong>{num(events.length)}</strong></div><div><small>Скидок использовано</small><strong>{money(events.reduce((sum,e)=>sum+e.discount,0))}</strong></div></div><ol className="launch-instructions"><li>Запустите демо — будет выбрана первая разрешённая дата акции.</li><li>Откройте кассу, выберите покупателя с предложением и примените купон.</li><li>Проверьте скидку и историю операции. Завершите демо после проверки.</li></ol><div className="launch-actions">{['scheduled','paused'].includes(c.status)&&<Button primary disabled={!at||!canOperate} onClick={activate}><Play size={16}/>{c.status==='paused'?'Возобновить демо':'Запустить демо'}</Button>}{c.status==='active'&&<><Button primary onClick={onCash}><ShoppingCart size={16}/>Проверить в демо-кассе</Button><Button disabled={!canOperate} onClick={()=>state.updateCampaign(c.id,{status:'paused'},'Демо на паузе')}><Pause size={16}/>Пауза</Button></>}{!['completed','archived'].includes(c.status)&&<Button disabled={!canOperate} onClick={()=>setFinish(true)}><Check size={16}/>Завершить демо</Button>}</div>{!at&&<p className="error-box">В сроках акции нет разрешённого дня. Создайте копию и исправьте расписание.</p>}{finish&&<Modal title="Завершить демо?" onClose={()=>setFinish(false)}><p>Новые применения купонов остановятся. История проверок сохранится.</p><div className="modal-actions"><Button onClick={()=>setFinish(false)}>Отмена</Button><Button primary onClick={()=>{state.updateCampaign(c.id,{status:'completed'},'Демо завершено');setFinish(false);}}>Завершить</Button></div></Modal>}</section>;
}
