import {visibleCampaigns} from './campaignLibrary';
import {useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ArrowRight,Download} from 'lucide-react';
import {useStore} from './store';
import {couponEngagement} from './couponEngagement';
import {num,dateRu,type Receipt} from './domain';
import {Button,Field,Modal,csv} from './ui';
export function CouponResults(){const state=useStore(),campaigns=visibleCampaigns(state.campaigns,state.showExamples),{id}=useParams(),navigate=useNavigate(),[selected,setSelected]=useState(id||campaigns[0]?.id||''),[window,setWindow]=useState(14),[receipt,setReceipt]=useState<Receipt|null>(null);const c=campaigns.find(c=>c.id===(id||selected))||(!id?campaigns[0]:undefined);const r=useMemo(()=>c?couponEngagement(c,state.data!,state.events,state.returns,window):null,[c,state.data,state.events,state.returns,window]);if(!c||!r)return <section className="panel empty"><h2>Здесь появится эффект купонов</h2><p>Сначала создайте и назначьте купон.</p><Button primary onClick={()=>navigate('/campaigns/new')}>Создать купон</Button></section>;return <>
 <div className="panel results-controls"><Field label="Кампания"><select value={c.id} onChange={e=>{setSelected(e.target.value);if(id)navigate('/results/'+e.target.value);}}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Окно наблюдения"><select value={window} onChange={e=>setWindow(Number(e.target.value))}>{[7,14,28].map(n=><option key={n} value={n}>{n} дней</option>)}</select></Field><Button onClick={()=>navigate('/campaigns/'+c.id)}>К кампании<ArrowRight size={16}/></Button><Button disabled={!r.rows.length} onClick={()=>csv(r.rows.map(x=>({Покупатель:x.customerId,Группа:x.group,Визитов_до:x.before,Визитов_после:x.after,Использовал_купон:x.redeemed,Вернулся_за_7_дней:x.mature?x.repeat:'Недостаточно данных'})),'coupon-engagement.csv')}><Download size={16}/>Экспорт</Button></div>
 <div className="section-gap"><span className="section-eyebrow">ЭФФЕКТ ПРЕДЛОЖЕНИЯ</span><h2>Меняется ли поведение</h2><p>{r.elapsed?`${dateRu(r.from)} — ${dateRu(r.through)} · ${r.elapsed} из ${window} дней`:'Покупок после старта пока нет в наборе.'}</p></div>{!c.assignments.length&&<div className="warning-box">У кампании пока нет назначений. Показатели появятся после запуска и применения купонов.</div>}{!!r.unlinked&&<div className="warning-box">Не удалось связать с назначением {r.unlinked} чеков. Они исключены из результата.</div>}
 <div className="engagement-kpis">{[['Использовали купон',r.redeemers],['Доля применений',r.offerGroup.n?num(r.redeemers/r.offerGroup.n*100,1)+'%':'—'],['Дополнительных товаров',r.baskets.length?r.additional:'—'],['Вернулись за 7 дней',r.repeatRate===null?'—':num(r.repeatRate*100,1)+'%']].map(([label,value])=><div className="panel" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="muted">Полные 7 дней после применения наблюдались у {r.repeatEligible} покупателей. Возвраты исключены из количества дополнительных товаров.</p>
 <section className="panel section-gap"><div className="split"><h2>Купон и контрольная группа</h2><span className="badge">{r.complete?'Окно собрано':'Наблюдение продолжается'}</span></div><div className="table-scroll"><table><thead><tr><th>Показатель</th><th>Купон</th><th>Без купона</th></tr></thead><tbody><tr><td>Назначено участников</td><td>{r.offerGroup.n}</td><td>{r.controlGroup.n}</td></tr><tr><td>Совершили покупку</td><td>{r.offerGroup.visitors}</td><td>{r.controlGroup.visitors}</td></tr><tr><td>Визитов на участника до</td>{[r.offerGroup,r.controlGroup].map((g,i)=><td key={i}>{r.baselineComplete&&g.before!==null?num(g.before,2):'Нет полного периода'}</td>)}</tr><tr><td>Визитов на участника после</td>{[r.offerGroup,r.controlGroup].map((g,i)=><td key={i}>{r.elapsed&&g.after!==null?num(g.after,2):'—'}</td>)}</tr></tbody></table></div><p>Сравниваются одинаковые периоды и все назначенные участники, включая тех, кто не пришёл. Это наблюдение; причинный эффект и статистическая надёжность не подтверждены.</p></section>
 <section className="panel section-gap"><h2>Что покупают вместе с купоном</h2>{!r.baskets.length?<div className="empty">Примените купон в демо-кассе или импортируйте чеки с coupon_id и assignment_id.</div>:<div className="table-scroll"><table><thead><tr><th>Чек</th><th>Покупатель</th><th>Дополнительных товаров</th><th>Возвращено</th><th/></tr></thead><tbody>{r.baskets.slice(0,100).map(b=><tr key={b.receipt.id}><td>{b.receipt.id}</td><td>#{b.receipt.customerId}</td><td>{b.additional}</td><td>{b.returned}</td><td><Button onClick={()=>setReceipt(b.receipt)}>Состав чека</Button></td></tr>)}</tbody></table></div>}</section>
 {receipt&&<Modal title="Состав чека с купоном" onClose={()=>setReceipt(null)}><p>#{receipt.customerId} · {dateRu(receipt.at)}</p><table><thead><tr><th>Товар</th><th>Количество</th><th>В условии купона</th></tr></thead><tbody>{receipt.lines.map(l=><tr key={l.id}><td>{state.data!.products.find(p=>p.id===l.productId)?.name||l.productId}</td><td>{l.quantity}</td><td>{((c.snapshot?.offer||c.offer).category===null?l.productId===(c.snapshot?.offer||c.offer).productId:state.data!.products.find(p=>p.id===l.productId)?.category===(c.snapshot?.offer||c.offer).category)?'Да':'Дополнительный товар'}</td></tr>)}</tbody></table></Modal>}</>;}
