export const DEMO_NOW='2026-09-14T10:00:00+03:00';
export const DAY=86400000;
export const categories=['Разливные напитки','Напитки в упаковке','Снеки','Безалкогольные'];
export const storeNames=['Арбат','Сокол','Таганская','Хамовники','Бауманская','Марьино','Измайлово','Митино','Перово','Тверская','Строгино','Бутово'];
export const stores=storeNames.map((name,i)=>({id:`S${i+1}`,name}));
export interface Product {id:string;name:string;category:number;price:number;cost:number|null;unit:string}
export interface Line {id:string;productId:string;quantity:number;price:number;discount:number;cost:number|null;originalLineId?:string}
export interface Receipt {id:string;storeId:string;customerId:string|null;at:string;type:'sale'|'return';originalId?:string;lines:Line[]}
export interface Customer {id:string;birthDate:string|null;consent:boolean;channel:boolean;contacts:number;storeId:string;receipts:Receipt[]}
export interface Dataset {schemaVersion:number;customers:Customer[];products:Product[];receipts:Receipt[];start:string;label:string}
export interface Filters {from:string;to:string;stores:string[];category?:number;product?:string;discount?:string;known?:string;min?:number;returns?:string}
export const DEFAULT_FILTERS:Filters={from:'2026-08-17',to:'2026-09-13',stores:[]};
export const localDay=(at:string)=>new Date(new Date(at).getTime()+3*3600000).toISOString().slice(0,10);
export const dayStart=(s:string)=>Date.parse(s+'T00:00:00+03:00');
export const addDays=(s:string,n:number)=>new Date(Date.parse(s+'T12:00:00Z')+n*DAY).toISOString().slice(0,10);
export const dateRu=(s:string,short=false)=>new Date(s.includes('T')?s:s+'T12:00:00+03:00').toLocaleDateString('ru-RU',{day:'numeric',month:short?'short':'long',timeZone:'Europe/Moscow'});
export const money=(v:number,digits=0)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(v/100)+' ₽';
export const num=(v:number,digits=0)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:digits}).format(v);
export const compact=(v:number)=>Math.abs(v)>=100000000?num(v/100000000,2)+' млн ₽':money(v);
export const lineNet=(l:Line)=>l.price*l.quantity-l.discount;
export const receiptNet=(r:Receipt)=>r.lines.reduce((a,l)=>a+lineNet(l),0)*(r.type==='return'?-1:1);
export function rng(seed:number){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function seedData(progress?:(n:number)=>void):Dataset {
 const random=rng(1042026);const integer=(a:number,b:number)=>a+Math.floor(random()*(b-a+1));
 const names=[['Светлый сорт','Янтарный сорт','Тёмный сорт','Пшеничный сорт'],['Классический вкус','Мягкий вкус','Оригинальный вкус','Лёгкий вкус'],['Чипсы с солью','Фисташки','Арахис','Сухарики','Начос'],['Лимонад лимон','Манго и маракуйя','Минеральная вода','Холодный чай']];
 const products:Product[]=Array.from({length:192},(_,i)=>{const cat=i%4;const price=(cat===2?190:cat===3?120:240)+Math.floor(i/4)*10;return{id:`P${String(i+1).padStart(3,'0')}`,name:names[cat][Math.floor(i/4)%names[cat].length]+(i>19?` · ${100+Math.floor(i/4)*10} ${cat===2?'г':'мл'}`:''),category:cat,price:price*100,cost:i===2?11500:Math.round(price*100*[.66,.74,.55,.63][cat]),unit:'шт.'};});
 products[2]={...products[2],name:'Чипсы с солью · 100 г',price:19000,cost:11500};
 const customers:Customer[]=Array.from({length:16000},(_,i)=>({id:`${String(i+1).padStart(5,'0')}`,birthDate:i%11===0?null:`${1970+i%37}-${String(i%12+1).padStart(2,'0')}-15`,consent:i%8!==0,channel:i%13!==0,contacts:i%9===0?3:0,storeId:`S${i%12+1}`,receipts:[]}));
 const receipts:Receipt[]=[];let id=0;
 for(let d=0;d<120;d++){
  const day=addDays('2026-05-17',d);const week=new Date(day+'T12:00:00Z').getUTCDay();const weight=[.78,.82,.87,.94,1.02,1.43,1.33][week];
  const count=Math.round((760+d*1.15)*weight);
  for(let j=0;j<count;j++){
   const anonymous=random()<.2;const cohort=(week===5||week===6)&&random()<.75;const ci=cohort?integer(0,3839):integer(3840,15999);const c=customers[ci];const category=ci<3840?[0,1,3][integer(0,2)]:integer(0,3);
   const lines:Line[]=Array.from({length:integer(1,3)},(_,k)=>{const cat=k===0?category:(ci<3840?[0,1,3][integer(0,2)]:integer(0,3));const p=products[integer(0,16)*4+cat];const quantity=integer(1,2);return{id:`L${id}-${k}`,productId:p.id,quantity,price:p.price,discount:random()<.12?Math.round(p.price*quantity*.05):0,cost:p.cost===null?null:p.cost*quantity};});
   const r:Receipt={id:`R${++id}`,storeId:random()<.77?c.storeId:`S${integer(1,12)}`,customerId:anonymous?null:c.id,at:`${day}T${String(integer(10,22)).padStart(2,'0')}:${String(integer(0,59)).padStart(2,'0')}:00+03:00`,type:'sale',lines};
   receipts.push(r);if(!anonymous)c.receipts.push(r);
   if(random()<.008){const ret:Receipt={...r,id:`RT${id}`,type:'return',originalId:r.id,lines:[{...lines[0],id:`RL${id}`,originalLineId:lines[0].id}]};receipts.push(ret);if(!anonymous)c.receipts.push(ret);}
  }if(d%12===0)progress?.(Math.round(d/120*100));
 }return{schemaVersion:2,customers,products,receipts,start:'2026-05-17',label:'Демонстрационный набор'};
}
export function selectReceipts(data:Dataset,f:Filters){const from=dayStart(f.from),to=dayStart(addDays(f.to,1));return data.receipts.filter(r=>{const t=Date.parse(r.at);return t>=from&&t<to&&(!f.stores.length||f.stores.includes(r.storeId))&&(!f.known||f.known==='all'||(f.known==='yes')===!!r.customerId)&&(!f.returns||f.returns==='all'||(f.returns==='yes')===(r.type==='return'))&&(!f.min||Math.abs(receiptNet(r))>=f.min)&&(!f.discount||f.discount==='all'||(f.discount==='yes')===r.lines.some(l=>l.discount>0));}).map(r=>({...r,lines:r.lines.filter(l=>(f.category===undefined||data.products.find(p=>p.id===l.productId)?.category===f.category)&&(!f.product||l.productId===f.product))})).filter(r=>r.lines.length);}
export function aggregate(receipts:Receipt[]){let revenue=0,cost=0,knownRevenue=0,lines=0,knownLines=0;const sales=new Set<string>(),people=new Set<string>();for(const r of receipts){const sign=r.type==='return'?-1:1;if(r.type==='sale'){sales.add(r.id);if(r.customerId)people.add(r.customerId);}for(const l of r.lines){const net=lineNet(l)*sign;revenue+=net;lines++;if(l.cost!==null){cost+=l.cost*sign;knownRevenue+=net;knownLines++;}}}return{revenue,cost,profit:knownRevenue-cost,count:sales.size,customers:people.size,average:sales.size?Math.round(revenue/sales.size):0,coverage:lines?knownLines/lines:0,margin:knownRevenue?(knownRevenue-cost)/knownRevenue:null};}
export function report(data:Dataset,f:Filters){const current=selectReceipts(data,f),length=Math.round((dayStart(f.to)-dayStart(f.from))/DAY)+1,previousFilters={...f,from:addDays(f.from,-length),to:addDays(f.from,-1)},previous=selectReceipts(data,previousFilters);const group=(rs:Receipt[],key:(r:Receipt)=>string)=>{const out=new Map<string,Receipt[]>();for(const r of rs){const k=key(r);if(!out.has(k))out.set(k,[]);out.get(k)!.push(r);}return out;};const days=group(current,r=>localDay(r.at)),prevDays=group(previous,r=>localDay(r.at)),byStore=group(current,r=>r.storeId),oldStore=group(previous,r=>r.storeId);
 return{...aggregate(current),previous:aggregate(previous),receipts:current,daily:Array.from({length},(_,i)=>({date:addDays(f.from,i),...aggregate(days.get(addDays(f.from,i))||[]),previous:aggregate(prevDays.get(addDays(previousFilters.from,i))||[])})),stores:stores.map(s=>({...s,...aggregate(byStore.get(s.id)||[]),previous:aggregate(oldStore.get(s.id)||[])})),categories:categories.map((name,i)=>({name,id:i,...aggregate(current.map(r=>({...r,lines:r.lines.filter(l=>data.products.find(p=>p.id===l.productId)?.category===i)})).filter(r=>r.lines.length))}))};
}
export type Field='count'|'spend'|'days'|'average'|'last'|'category'|'weekday'|'store'|'consent'|'channel'|'contacts'|'age';
export interface Rule {id:string;field:Field;op:string;value:string|number;window:number}
export interface Group {id:string;logic:'AND'|'OR'|'NOT';children:(Rule|Group)[]}
export const isGroup=(r:Rule|Group):r is Group=>'children'in r;
export const baseSegment:Group={id:'root',logic:'AND',children:[{id:'r1',field:'count',op:'gte',value:4,window:90},{id:'r2',field:'weekday',op:'gte',value:60,window:90},{id:'r3',field:'last',op:'lte',value:28,window:120},{id:'r4',field:'category',op:'not',value:2,window:60}]};
export const fields:Record<Field,{label:string;ops:string[]}>={count:{label:'Число чеков',ops:['gte','lte','eq']},spend:{label:'Сумма покупок, ₽',ops:['gte','lte']},days:{label:'Дни с покупками',ops:['gte','lte']},average:{label:'Средний чек, ₽',ops:['gte','lte']},last:{label:'Дней с покупки',ops:['gte','lte']},category:{label:'Категория',ops:['yes','not']},weekday:{label:'Чеки в пт/сб, %',ops:['gte','lte']},store:{label:'Основной магазин',ops:['eq']},consent:{label:'Согласие',ops:['yes','not']},channel:{label:'Доступен канал',ops:['yes','not']},contacts:{label:'Получено предложений',ops:['gte','lte']},age:{label:'Известный возраст',ops:['gte','lte']}};
export const ops:Record<string,string>={gte:'не меньше',lte:'не больше',eq:'равно',yes:'есть',not:'нет'};
const statsCache=new WeakMap<Customer,Map<number,any>>();
export function customerStats(c:Customer,window=90):ReturnType<typeof computeCustomerStats>{let cache=statsCache.get(c);if(!cache){cache=new Map();statsCache.set(c,cache);}if(cache.has(window))return cache.get(window);const result=computeCustomerStats(c,window);cache.set(window,result);return result;}
function computeCustomerStats(c:Customer,window=90){const start=dayStart('2026-09-14')-window*DAY;const rs=c.receipts.filter(r=>Date.parse(r.at)>=start&&Date.parse(r.at)<dayStart('2026-09-14'));const sale=rs.filter(r=>r.type==='sale');const last=c.receipts.filter(r=>r.type==='sale').reduce((a,r)=>Math.max(a,dayStart(localDay(r.at))),0);const cats=[0,0,0,0];const weekdays=[0,0,0,0,0,0,0];for(const r of sale){weekdays[new Date(localDay(r.at)+'T12:00Z').getUTCDay()]++;for(const l of r.lines)cats[(Number(l.productId.slice(1))-1)%4]+=lineNet(l);}return{...aggregate(rs),days:new Set(sale.map(r=>localDay(r.at))).size,last:last?Math.round((dayStart('2026-09-14')-last)/DAY):null,lastDate:last?new Date(last+3*3600000).toISOString().slice(0,10):null,cats,weekdays,favorite:cats.indexOf(Math.max(...cats)),weekend:sale.length?(weekdays[5]+weekdays[6])/sale.length*100:null};}
export function validateGroup(g:Group,depth=0):string[]{const errors:string[]=[];if(depth>2)errors.push('Поддерживается три уровня групп');if(!g.children.length)errors.push('Добавьте условие: пустая группа не включает покупателей');for(const r of g.children){if(isGroup(r))errors.push(...validateGroup(r,depth+1));else if(!fields[r.field]||!fields[r.field].ops.includes(r.op)||!Number.isFinite(Number(r.value))&&r.field!=='store'||Number(r.value)<0||r.window<1||r.window>120)errors.push('Проверьте поле, оператор, значение и окно 1–120 дней');}return errors;}
export function matches(c:Customer,g:Group,dataStart='2026-05-17'):boolean {if(validateGroup(g).length)return false;const cache=new Map<number,ReturnType<typeof customerStats>>();function test(n:Rule|Group):boolean{if(isGroup(n)){const vals=n.children.map(test);return n.logic==='AND'?vals.every(Boolean):n.logic==='OR'?vals.some(Boolean):!vals.every(Boolean);}if(dayStart('2026-09-14')-dayStart(dataStart)<n.window*DAY)return false;let s=cache.get(n.window);if(!s){s=customerStats(c,n.window);cache.set(n.window,s);}let v:number|string|boolean|null=0;switch(n.field){case'count':v=s.count;break;case'spend':v=s.revenue/100;break;case'days':v=s.days;break;case'average':v=s.count?s.average/100:null;break;case'last':v=s.last;break;case'weekday':v=s.weekend;break;case'category':v=s.cats[Number(n.value)]>0;break;case'store':v=c.storeId;break;case'consent':v=c.consent;break;case'channel':v=c.channel;break;case'contacts':v=c.contacts;break;case'age':v=c.birthDate?2026-Number(c.birthDate.slice(0,4))-(c.birthDate.slice(5)>'09-14'?1:0):null;}if(v===null)return false;if(n.op==='yes')return !!v;if(n.op==='not')return !v;if(n.op==='eq')return String(v)===String(n.value);return n.op==='gte'?Number(v)>=Number(n.value):Number(v)<=Number(n.value);}return test(g);}
export function audience(data:Dataset,g:Group,storeIds:string[]=[],noChannel=false){const behavior=data.customers.filter(c=>matches(c,g,data.start));const channel=behavior.filter(c=>c.consent&&c.channel&&!noChannel);const frequency=channel.filter(c=>c.contacts<3);const stock=frequency.filter(c=>(!storeIds.length||storeIds.includes(c.storeId))&&c.storeId!=='S12');return{behavior,eligible:stock,excluded:[{reason:'Нет канала или согласия',count:behavior.length-channel.length},{reason:'Лимит контактов: 3 за 30 дней',count:channel.length-frequency.length},{reason:'Магазин вне акции или нет наличия',count:frequency.length-stock.length}]};}
export interface Offer {productId:string;category:number|null;kind:'percent'|'fixed';value:number;cap:number;minBasket:number;minMargin:number;once:boolean;stackable:boolean;stores:string[];from:string;to:string;weekdays:number[];hourFrom:number;hourTo:number;control:number;budget:number;channelCost:number}
export const defaultOffer:Offer={productId:'P003',category:null,kind:'percent',value:10,cap:5000,minBasket:0,minMargin:25,once:true,stackable:false,stores:stores.map(s=>s.id).filter(id=>id!=='S12'),from:'2026-09-16',to:'2026-09-24',weekdays:[3,4],hourFrom:10,hourTo:22,control:50,budget:25000000,channelCost:0};
export const economy=(p:Product,o:Offer)=>{const discount=Math.min(o.cap,o.kind==='percent'?Math.round(p.price*o.value/100):o.value*100,p.price);const price=p.price-discount;const profit=p.cost===null?null:price-p.cost;return{discount,price,profit,margin:profit===null||!price?null:profit/price*100};};
export function offerErrors(o:Offer,p:Product|undefined,n:number,products?:Product[]){const errors:string[]=[];if(!p)errors.push('Товар не найден');else {const e=economy(p,o);if(p.cost===null)errors.push('Неизвестна себестоимость товара');else if(e.margin===null||e.margin<o.minMargin)errors.push(`Маржа ${num(e.margin||0,2)}% ниже минимальной ${o.minMargin}%`);}if(o.category!==null&&products){const bad=products.filter(p=>p.category===o.category&&(p.cost===null||(economy(p,o).margin??-1)<o.minMargin));if(bad.length)errors.push(`В категории ${bad.length} товаров с неизвестной себестоимостью или недостаточной маржей`);}if(n<=0)errors.push('Нет доступных получателей');if(!o.stores.length)errors.push('Выберите магазин');if(o.stores.every(s=>s==='S12'))errors.push('В выбранных магазинах нет товара');if(!o.from||!o.to||o.from>o.to)errors.push('Проверьте даты начала и окончания');if(o.from&&o.to&&dayStart(o.to)-dayStart(o.from)>=90*DAY)errors.push('Срок кампании ограничен 90 днями');if(!o.weekdays.length||o.hourFrom>=o.hourTo||o.hourFrom<0||o.hourTo>24)errors.push('Проверьте дни и часы действия');if(o.value<=0||o.kind==='percent'&&o.value>100||o.cap<=0||o.minBasket<0)errors.push('Скидка, лимит и сумма корзины некорректны');if(o.control<=0||o.control>=100)errors.push('Контрольная группа должна быть от 1 до 99%');if(n*o.cap+n*o.channelCost>o.budget)errors.push(`Бюджет меньше обязательства ${money(n*o.cap+n*o.channelCost)}`);return errors;}
export function offerDates(o:Offer){if(!o.from||!o.to||!Number.isFinite(dayStart(o.from))||!Number.isFinite(dayStart(o.to))||o.from>o.to||!o.weekdays.length)return 'Укажите даты действия';const dates:string[]=[];for(let d=o.from;d<=o.to&&d<=addDays(o.from,89);d=addDays(d,1)){if(o.weekdays.includes(new Date(d+'T12:00:00Z').getUTCDay()))dates.push(d);if(dates.length>90)break;}const groups:string[][]=[];for(const d of dates){const last=groups.at(-1);if(last&&addDays(last.at(-1)!,1)===d)last.push(d);else groups.push([d]);}return groups.map(g=>g.length>1?`${g[0].slice(0,7)===g.at(-1)!.slice(0,7)?Number(g[0].slice(8)):dateRu(g[0])}–${dateRu(g.at(-1)!)}`:dateRu(g[0])).join(' и ');}
export interface Design {schemaVersion:1;brandId:string;brandVersion:number;templateId:string;asset:string;title:string;description:string;fontSize:number;align:'left'|'center';crop:{x:number;y:number;scale:number};showDescription:boolean;reverse:boolean;revision:number;variantId?:string;logo?:string;brandTokens?:{primary:string;ink:string;paper:string;font:string;pattern:string;fontUrl?:string}}
export const defaultDesign:Design={schemaVersion:1,brandId:'kvartal',brandVersion:1,templateId:'right',asset:'/assets/kvartal-right.png',title:'на любимые\nснеки',description:'Больше вкусных\nмоментов рядом',fontSize:28,align:'left',crop:{x:50,y:50,scale:1},showDescription:true,reverse:false,revision:1};
export const themes=[{id:'kvartal',name:'Квартал 12',primary:'#F25835',ink:'#191B1D',paper:'#F6F0E8',font:'Inter',asset:'/assets/kvartal-right.png'},{id:'copper',name:'Медный двор',primary:'#173D32',ink:'#F3E4BA',paper:'#F5F0E3',font:'Georgia',asset:'/assets/copper.png'},{id:'lemon',name:'Лимон & соль',primary:'#F2DB38',ink:'#191B1D',paper:'#FFFCDF',font:'Inter',asset:'/assets/lemon.png'}];
export interface Assignment {id:string;customerId:string;group:'offer'|'control';token:string;used:boolean}
export interface Campaign {id:string;name:string;status:'draft'|'scheduled'|'active'|'paused'|'completed'|'archived';step:number;rules:Group;offer:Offer;design:Design;assignments:Assignment[];personalId?:string;snapshot?:{offer:Offer;design:Design;rules:Group};created:string}
export const statusLabels={draft:'Черновик',scheduled:'Запланирована',active:'Активна в демо',paused:'Пауза',completed:'Завершена',archived:'Архив'};
export function campaignsSeed():Campaign[]{return[{id:'CP-104',name:'Вернуть в будни',status:'draft',step:0,rules:structuredClone(baseSegment),offer:{...defaultOffer},design:{...defaultDesign},assignments:[],created:DEMO_NOW},{id:'CP-105',name:'Вернуться за любимым',status:'draft',step:1,rules:{id:'root',logic:'AND',children:[{id:'r1',field:'last',op:'gte',value:21,window:90}]},offer:{...defaultOffer,kind:'fixed',value:50,minBasket:50000,productId:'P004'},design:{...defaultDesign,asset:'/assets/kvartal-air.png',title:'на новые\nвпечатления'},assignments:[],created:DEMO_NOW},{id:'CP-097',name:'Попробовать новое',status:'completed',step:4,rules:structuredClone(baseSegment),offer:{...defaultOffer,from:'2026-08-17',to:'2026-09-13',weekdays:[0,1,2,3,4,5,6]},design:{...defaultDesign,asset:'/assets/kvartal-scene.png',title:'откройте\nновый вкус'},assignments:[],created:DEMO_NOW}];}
export function assign(ids:string[],campaignId:string,control:number){const random=rng([...campaignId].reduce((s,c)=>s+c.charCodeAt(0),104));const shuffled=[...ids].sort();for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}const n=Math.round(shuffled.length*control/100);return shuffled.map((customerId,i):Assignment=>({id:`${campaignId}-${customerId}`,customerId,group:i<n?'control':'offer',token:`DEMO-${campaignId}-${customerId}-${Math.floor(random()*1e9).toString(36)}`,used:false}));}
export interface Redemption {operationId:string;assignmentId:string;campaignId:string;receipt:Receipt;discount:number;returnedLines:string[]}
export function allocateDiscount(lines:Line[],amount:number){const total=lines.reduce((s,l)=>s+lineNet(l),0);let left=amount;return lines.map((l,i)=>{const d=i===lines.length-1?left:Math.floor(amount*lineNet(l)/total);left-=d;return{...l,discount:l.discount+d};});}
export function redeem(c:Campaign,a:Assignment|undefined,cart:Line[],storeId:string,at:string,token:string,operationId:string,events:Redemption[]){const existing=events.find(e=>e.operationId===operationId);if(existing)return{event:existing};const o=c.snapshot?.offer||c.offer;if(c.status!=='active')return{error:'Кампания не активна в демо'};if(!a||a.group!=='offer'||a.token!==token)return{error:'Купон не назначен этому покупателю'};if(o.once&&(a.used||events.some(e=>e.assignmentId===a.id)))return{error:'Купон уже использован'};const d=localDay(at),time=new Date(Date.parse(at)+3*3600000);if(d<o.from||d>o.to||!o.weekdays.includes(time.getUTCDay())||time.getUTCHours()<o.hourFrom||time.getUTCHours()>=o.hourTo)return{error:'Купон не действует в выбранные дату и время'};if(!o.stores.includes(storeId))return{error:'Магазин не участвует в акции'};if(cart.some(l=>l.quantity<=0||!Number.isInteger(l.quantity)))return{error:'Количество должно быть целым и положительным'};if(!o.stackable&&cart.some(l=>l.discount>0))return{error:'Купон не совместим с другой скидкой'};const total=cart.reduce((s,l)=>s+lineNet(l),0);if(total<o.minBasket)return{error:`Минимальная корзина ${money(o.minBasket)}`};const selected=cart.filter(l=>o.category!==null?(Number(l.productId.slice(1))-1)%4===o.category:l.productId===o.productId);if(!selected.length)return{error:'В корзине нет подходящего товара'};if(selected.some(l=>l.cost===null))return{error:'Неизвестна себестоимость'};const base=selected.reduce((s,l)=>s+lineNet(l),0),discount=Math.min(base,o.cap,o.kind==='percent'?Math.round(base*o.value/100):Math.round(o.value*100));const discounted=allocateDiscount(selected,discount);if(discounted.some(l=>(lineNet(l)-(l.cost||0))/lineNet(l)*100<o.minMargin))return{error:'Маржа корзины ниже разрешённой'};const all=cart.map(l=>discounted.find(x=>x.id===l.id)||l);return{event:{operationId,assignmentId:a.id,campaignId:c.id,receipt:{id:`SIM-${operationId}`,storeId,customerId:a.customerId,at,type:'sale' as const,lines:all},discount,returnedLines:[]}};}
export function returnReceipt(event:Redemption,lineIds:string[]):Receipt{const lines=event.receipt.lines.filter(l=>lineIds.includes(l.id)&&!event.returnedLines.includes(l.id)).map(l=>({...l,id:'RETURN-'+l.id,originalLineId:l.id}));if(!lines.length)throw new Error('Эти строки уже возвращены');return{...event.receipt,id:'RETURN-'+event.operationId+'-'+event.returnedLines.length,type:'return',originalId:event.receipt.id,lines};}
