import {engagementReport as report} from './engagement';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,CheckCheck,Compass,Download,Expand,Layers,MapPin,Minus,Plus,Search,SlidersHorizontal,Store,Target,X} from 'lucide-react';
import {useStore} from './store';
import {dateRu,num,stores,type Filters} from './domain';
import {csv} from './ui';
import {createStoreCampaign,districts,growthPercent,initialMapSelection,mapStores,selectedFilters,selectionTotals,storeSearch,type MapMetric} from './networkMapData';
import {storeAverageCheck} from './storeAverageCheck';
import {MapAverageCheck} from './MapAverageCheck';
import {NetworkMapCanvas,type MapHandle} from './NetworkMapCanvas';

const metricNames={customers:'Покупатели',count:'Визиты',growth:'Динамика визитов'};
const growthLabel=(value:number|null)=>value===null?'Нет сравнения':`${value>=0?'+':''}${num(value,1)}%`;

export function NetworkMap({filters,onFilters}:{filters:Filters;onFilters:(filters:Filters)=>void}){
 const data=useStore(s=>s.data)!,notify=useStore(s=>s.notify),name=useStore(s=>s.settings.name),navigate=useNavigate(),location=useLocation();
 const [selected,setSelected]=useState(()=>initialMapSelection(filters.stores)),[focused,setFocused]=useState<string|null>(null),[query,setQuery]=useState(''),[district,setDistrict]=useState('Все районы'),[sort,setSort]=useState('count'),[metric,setMetric]=useState<MapMetric>('count'),[full,setFull]=useState(false),[schematic,setSchematic]=useState(false),[mapStatus,setMapStatus]=useState('loading'),[mapAttempt,setMapAttempt]=useState(0);
 const map=useRef<MapHandle>(null),root=useRef<HTMLDivElement>(null),expandButton=useRef<HTMLButtonElement>(null),focusClose=useRef<HTMLButtonElement>(null);
 const storeKey=filters.stores.join(',');useEffect(()=>setSelected(initialMapSelection(filters.stores)),[storeKey]);
 const all=useMemo(()=>report(data,{...filters,stores:[]}),[data,filters.from,filters.to,filters.category,filters.product,filters.discount,filters.known,filters.min,filters.returns]);
 const rows=useMemo(()=>mapStores.map(store=>{const stats=all.stores.find(row=>row.id===store.id)!;return {...store,...stats,growth:growthPercent(stats.count,stats.previous.count)};}),[all]);
 const shown=useMemo(()=>rows.filter(row=>(district==='Все районы'||row.district===district)&&`${row.name} ${row.area} ${row.id}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ru'):sort==='growth'?(b.growth??-Infinity)-(a.growth??-Infinity):b.count-a.count),[rows,district,query,sort]);
 const totals=useMemo(()=>selectionTotals(rows,selected),[rows,selected]),focusedStore=rows.find(s=>s.id===focused);
 const averageCheck=useMemo(()=>focused?storeAverageCheck(data,filters,focused):null,[data,focused,filters.from,filters.to]);
 const labels=useMemo(()=>Object.fromEntries(rows.map(s=>[s.id,metric==='customers'?num(s.customers):metric==='count'?num(s.count):growthLabel(s.growth)])),[rows,metric]);
 const applied=initialMapSelection(filters.stores),changed=selected.length!==applied.length||selected.some(id=>!applied.includes(id));
 useEffect(()=>{if(!full)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const lastFocus=document.activeElement as HTMLElement;root.current?.querySelector<HTMLButtonElement>('.map-back')?.focus();
  const handle=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setFull(false);}if(e.key==='Tab'){const items=[...root.current!.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href]')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
  window.addEventListener('keydown',handle);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',handle);lastFocus?.focus();};
 },[full]);
 function pick(id:string){setFocused(id);setSelected(current=>current.length===stores.length?[id]:current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);}
 function analytics(ids=selected){if(!ids.length)return;navigate('/customers');}
 function createCampaign(){if(!selected.length)return;const c=createStoreCampaign(selected,'CP-'+crypto.randomUUID().slice(0,8));useStore.getState().addCampaign(c);navigate('/campaigns/'+c.id);notify('Черновик создан · магазины перенесены из карты');}
 function exportSelection(){csv(rows.filter(s=>selected.includes(s.id)).map(s=>({Магазин:s.name,Район:s.area,С:filters.from,По:filters.to,Визиты:s.count,Покупатели:s.customers,Динамика_проц:s.growth===null?'':Number(s.growth.toFixed(1)),Координаты:'Демонстрационные',Широта:s.lat,Долгота:s.lng})));}
 return <div ref={root} className={'network-map-page map-first '+(full?'is-fullscreen':'')} role={full?'dialog':undefined} aria-modal={full?true:undefined} aria-label="Магазины на карте">
  {full&&<header className="map-fullscreen-heading"><button className="map-back" onClick={()=>setFull(false)}><ArrowLeft size={18}/>Вернуться в панель</button><b>Сеть на карте</b><span>{name}</span></header>}
  <div className="network-map-workspace">
   <section className="map-stage" aria-label="Интерактивная карта">
    <NetworkMapCanvas key={mapAttempt} ref={map} selected={selected} focused={focused} labels={labels} onPick={pick} onStatus={setMapStatus} schematic={schematic}/>
    <div className="map-topbar"><span className="map-city"><MapPin size={17}/><b>Москва</b><span>12 точек</span></span><div className="map-metric-switch" aria-label="Показатель на маркерах">{(Object.keys(metricNames) as MapMetric[]).map(key=><button key={key} aria-pressed={metric===key} className={metric===key?'active':''} onClick={()=>setMetric(key)}>{metricNames[key]}</button>)}</div></div>
    <div className="map-controls"><button className="map-icon-button" aria-label="Приблизить карту" title="Приблизить" onClick={()=>map.current?.zoom(1)}><Plus size={19}/></button><button className="map-icon-button" aria-label="Отдалить карту" title="Отдалить" onClick={()=>map.current?.zoom(-1)}><Minus size={19}/></button><span/><button className="map-icon-button" aria-label="Показать всю сеть" title="Показать всю сеть" onClick={()=>{setFocused(null);map.current?.fit();}}><Target size={18}/></button><button className="map-icon-button" aria-label="Наклонить карту" title={mapStatus==='live'?'Объёмный ракурс':'Ракурс доступен на географической карте'} disabled={mapStatus!=='live'} onClick={()=>map.current?.tilt()}><Layers size={18}/></button><button ref={expandButton} className="map-icon-button" aria-label={full?'Вернуться в панель':'Открыть карту на весь экран'} title={full?'Вернуться':'На весь экран'} onClick={()=>setFull(!full)}>{full?<X size={18}/>:<Expand size={18}/>}</button></div>
    <div className="map-caption"><span className="map-north"><Compass size={16}/>N</span><span>{mapStatus==='live'?'Карта Москвы':mapStatus==='loading'?'Загружаем карту Москвы':'Схема сети · условная география'}</span><button onClick={()=>{if(mapStatus==='fallback'){setMapAttempt(n=>n+1);return;}setSchematic(s=>!s);}}>{mapStatus==='fallback'?'Повторить загрузку':schematic?'Загрузить карту':'Лёгкая схема'}</button></div>
    {focusedStore&&<section className="map-point-card" aria-label={'Карточка магазина '+focusedStore.name}><div className="map-point-heading"><span className="map-point-icon"><Store size={20}/></span><div><small>МАГАЗИН {focusedStore.id.slice(1).padStart(2,'0')}</small><h3>{focusedStore.name}</h3></div><button ref={focusClose} className="map-icon-button" aria-label="Закрыть карточку магазина" onClick={()=>setFocused(null)}><X size={16}/></button></div><p>{focusedStore.area} · демонстрационное расположение</p>{averageCheck&&<MapAverageCheck key={focusedStore.id+filters.from+filters.to} report={averageCheck}/>}<div className="map-point-stats"><span>Чеки <b>{num(focusedStore.count)}</b></span><span>Покупатели <b>{num(focusedStore.customers)}</b></span></div><div className="map-point-actions"><button onClick={()=>{setSelected([focusedStore.id]);notify('Выбран только магазин «'+focusedStore.name+'»');}}><Check size={15}/>Только этот</button><button onClick={()=>analytics([focusedStore.id])}>Покупатели<ArrowUpRight size={15}/></button></div></section>}
    {!focusedStore&&<div className="map-instruction"><span><MapPin size={17}/></span><div><b>Выберите точки на карте</b><p>или отметьте магазины в списке ниже</p></div></div>}
   </section>
  </div>
  <footer className="map-selection-bar"><div className="map-selection-title"><span><CheckCheck size={21}/></span><div><b>{selected.length?selected.length===stores.length?'Выбрана вся сеть':`Выбрано магазинов: ${selected.length}`:'Выберите магазины'}</b><small>{selected.length?changed?'Выбор готов к применению':'Текущий фильтр панели':'Нажмите на точки или отметьте их в списке'}</small></div></div><div className="map-selection-actions"><button className="map-reset" onClick={()=>{setSelected(stores.map(s=>s.id));setFocused(null);map.current?.fit();}}>Вся сеть</button><button className="map-apply" disabled={!selected.length||!changed} onClick={()=>{onFilters(selectedFilters(filters,selected));notify('Выбор магазинов применён к панели');}}>Применить</button><button className="map-analytics" disabled={!selected.length} onClick={()=>analytics()}>Покупатели<ArrowUpRight size={16}/></button><button className="map-create" disabled={!selected.length} onClick={createCampaign}><Plus size={17}/>Создать кампанию</button></div></footer>
  <section className="map-summary" aria-label="Показатели выбранных магазинов">
   <div className="map-intro"><span className="map-eyebrow"><i/>ГЕОГРАФИЯ ВАШЕЙ СЕТИ</span><h2>Весь город.<br/><span>В одном поле зрения.</span></h2><p>{dateRu(filters.from,true)} — {dateRu(filters.to,true)} · {selected.length===stores.length?'Вся сеть':selected.length+' из '+stores.length+' магазинов'}</p></div>
   <div className="map-summary-metrics"><div><span>Посещения выбранных точек</span><strong>{selected.length?num(totals.count):'—'}</strong><small className={totals.growth!==null&&totals.growth<0?'falling':''}>{selected.length?growthLabel(totals.growth):'Выберите магазины'}<span> к прошлому периоду</span></small></div><div><span>Покупатели</span><strong>{selected.length?num(totals.customers):'—'}</strong><small>Уникальные покупатели с ID</small></div></div>
  </section>
   <aside className="map-directory">
    <div className="map-directory-heading"><div><h3>Магазины</h3><span>{shown.length} из {stores.length} точек</span></div><button className="map-icon-button" aria-label="Экспорт выбранных магазинов" title="Экспорт CSV" disabled={!selected.length} onClick={exportSelection}><Download size={17}/></button></div>
    <label className="map-search"><Search size={17}/><input placeholder="Найти магазин или район" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Поиск магазинов"/>{query&&<button aria-label="Очистить поиск" onClick={()=>setQuery('')}><X size={14}/></button>}</label>
    <div className="map-list-filters"><label><MapPin size={13}/><select aria-label="Район магазинов" value={district} onChange={e=>setDistrict(e.target.value)}>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label><SlidersHorizontal size={13}/><select aria-label="Порядок магазинов" value={sort} onChange={e=>setSort(e.target.value)}><option value="count">По посещениям</option><option value="growth">По динамике</option><option value="name">По названию</option></select></label></div>
    <div className="map-list-select"><label><input type="checkbox" aria-label="Выбрать все найденные магазины" checked={shown.length>0&&shown.every(s=>selected.includes(s.id))} disabled={!shown.length} onChange={e=>setSelected(current=>e.target.checked?[...new Set([...current,...shown.map(s=>s.id)])]:current.filter(id=>!shown.some(s=>s.id===id)))}/><span>Выбрать найденные</span></label><span>{selected.length} выбрано</span></div>
    <div className="map-store-list">{shown.map(row=><article key={row.id} className={'map-store-row '+(focused===row.id?'focused':'')}><label className="map-store-check"><input type="checkbox" checked={selected.includes(row.id)} aria-label={'Включить '+row.name+' в выбор'} onChange={()=>toggle(row.id)}/></label><button className="map-store-details" onClick={()=>{setFocused(row.id);root.current?.querySelector('.map-stage')?.scrollIntoView({behavior:document.documentElement.dataset.motion==='minimal'?'instant':'smooth',block:'start'});}} aria-label={'Открыть магазин '+row.name}><span className="map-store-top"><b>{row.name}</b><small>{row.id.slice(1).padStart(2,'0')}</small></span><span className="map-store-area">{row.district} · демо-точка</span><span className="map-store-bottom"><strong>{num(row.count)+' визитов'}</strong><em className={row.growth!==null&&row.growth<0?'falling':''}>{growthLabel(row.growth)}</em></span></button></article>)}{!shown.length&&<div className="map-empty"><Search size={24}/><b>Ничего не найдено</b><p>Попробуйте другое название или район.</p><button onClick={()=>{setQuery('');setDistrict('Все районы');}}>Сбросить поиск</button></div>}</div>
    <div className="map-directory-footer"><span className="map-demo-dot"/><p>Демо-сеть в Москве.<br/>Расположение точек условное.</p></div>
   </aside>

 </div>;
}
