import {SrezNavIcons} from './SrezNavIcons';
import {isExampleCampaign,visibleCampaigns} from './campaignLibrary';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Plus,Users,Ticket,Palette,Repeat2} from 'lucide-react';
import {useStore} from './store';
import {type Filters,num} from './domain';
import {CouponRenderer} from './Coupon';
import {NetworkMapTeaser} from './NetworkMapTeaser';
export function NetworkHome({filters}:{filters:Filters}){const state=useStore(),campaigns=visibleCampaigns(state.campaigns,state.showExamples),drafts=campaigns.filter(c=>c.status==='draft');return <>
 <section className="network-home-hero"><div><span className="section-eyebrow">{state.settings.name} · РАБОТА С ПОКУПАТЕЛЯМИ</span><h2>Знать привычки.<br/><span>Находить повод вернуться.</span></h2><p>Аудитории, предложения и купоны — от первой идеи до повторного визита.</p><Link className="button primary" to="/campaigns/new"><Plus size={18}/>Создать купон</Link></div><div className="home-orbit" aria-hidden="true"><SrezNavIcons.coupons size={84}/><i/><i/><i/></div></section>
 <div className="engagement-kpis">{[{label:'Покупателей в базе',value:num(state.data?.customers.length||0),to:'/customers',Icon:SrezNavIcons.customers},{label:'Активных акций',value:campaigns.filter(c=>c.status==='active').length,to:'/campaigns',Icon:SrezNavIcons.campaigns},{label:'Черновиков',value:drafts.length,to:'/coupons',Icon:SrezNavIcons.coupons},{label:'Применений купонов',value:state.events.filter(e=>campaigns.some(c=>c.id===e.campaignId)).length,to:'/results',Icon:SrezNavIcons.results}].map(k=><Link className="panel" key={k.label} to={k.to}><k.Icon size={20}/><strong>{k.value}</strong><span>{k.label}</span><ArrowUpRight size={15}/></Link>)}</div>
 <NetworkMapTeaser filters={filters}/><div className="home-scenarios"><Link className="panel" to="/customers"><span>01 / АУДИТОРИЯ</span><h3>Кому будет интересно</h3><p>Категории, возраст, пол, частота покупок и участие в программе.</p><ArrowUpRight/></Link><Link className="panel" to="/partners"><span>02 / СТИЛЬ</span><h3>Купон от партнёра</h3><p>Отдельные материалы, цвета и правила для каждого бренда.</p><ArrowUpRight/></Link><Link className="panel" to="/results"><span>03 / ПОВЕДЕНИЕ</span><h3>Что изменило предложение</h3><p>Применения, дополнительные товары и повторные визиты.</p><ArrowUpRight/></Link></div>
 <div className="split section-gap"><h2>Продолжить работу</h2><Link className="text-button" to="/coupons">Все купоны<ArrowUpRight size={16}/></Link></div><div className="campaign-grid">{drafts.slice(0,3).map(c=><article className="panel" key={c.id}><h3>{c.name}</h3>{isExampleCampaign(c)&&<span className="badge sample-badge">Образец</span>}<div className="section-gap"><CouponRenderer design={c.design} offer={c.offer} format="list"/></div><Link className="button section-gap" to={'/campaigns/'+c.id}>Продолжить настройку<ArrowUpRight size={16}/></Link></article>)}</div>{!drafts.length&&<div className="panel empty">Черновиков пока нет. Создайте купон или соберите аудиторию.</div>}<p className="muted section-gap">Демонстрационный набор. Отправка купонов в приложение и синхронизация с базой подключаются отдельно.</p>
 </>;}
