import {useEffect,useRef,useState} from 'react';
import {ImagePlus,Sparkles,Upload,X} from 'lucide-react';
import {api} from './store';
import {refreshBrands,type BrandChoice} from './brandLibrary';
import {brandChoice} from './brandCatalog';
import {initialProfile} from './initialBrandProfile';
import type {BrandProfile} from './brandSchema';
import {defaultDesign,defaultOffer} from './domain';
import {uploadAssets} from './uploads';
import {assetURL} from './runtime';
import {Button,Field,Modal} from './ui';
import {CouponRenderer} from './Coupon';

const starter=()=>{const p=initialProfile({id:'partner-draft',name:'',primary:'#31594A',ink:'#1D1D1B',paper:'#FFF8EC',font:'Inter',asset:'/assets/brand-neutral.svg'});return {...p,imagery:{description:'',lighting:'Мягкий естественный свет',focus:'Товар и предложение'},provenance:[]};};
const paletteFields=[['primary','Основной цвет'],['accent','Акцент'],['canvas','Фон купона'],['onPrimary','Текст']] as const;
export function PartnerStyleModal({onClose,onSaved}:{onClose:()=>void;onSaved:(brand:BrandChoice)=>void}){
 const [profile,setProfile]=useState<BrandProfile>(starter),[logo,setLogo]=useState<File|null>(null),[logoUrl,setLogoUrl]=useState(''),[files,setFiles]=useState<File[]>([]),[assets,setAssets]=useState<any[]>([]),[colors,setColors]=useState<string[]>([]),[saving,setSaving]=useState(false),[job,setJob]=useState<string|null>(null),[error,setError]=useState(''),[status,setStatus]=useState<any>(null);
 const brandId=useRef<string|null>(null),activeJob=useRef<string|null>(null),live=useRef(true),pending=useRef(false);
 useEffect(()=>{live.current=true;api('/status').then(setStatus).catch(()=>{});return()=>{live.current=false;const id=activeJob.current;if(id)void api('/jobs/'+id+'/cancel',{}).catch(()=>{});};},[]);
 useEffect(()=>{if(!logo)return;const url=URL.createObjectURL(logo);setLogoUrl(url);return()=>URL.revokeObjectURL(url);},[logo]);
 useEffect(()=>{if(!job)return;let stopped=false,timer:ReturnType<typeof setTimeout>,failures=0;
  async function poll(){try{const result=await api('/jobs/'+job);if(stopped)return;failures=0;if(['ready','failed','cancelled','interrupted'].includes(result.status)){setJob(null);activeJob.current=null;if(result.profile){setProfile(result.profile);setError('');}else setError(result.error?.message||'Анализ остановлен. Можно настроить стиль вручную.');return;}timer=setTimeout(poll,1500);}catch(e){if(stopped)return;if(++failures>5){setError((e as Error).message);void api('/jobs/'+job+'/cancel',{}).catch(()=>{});activeJob.current=null;setJob(null);}else timer=setTimeout(poll,3000*failures);}}
  void poll();return()=>{stopped=true;clearTimeout(timer);};
 },[job]);
 function addFiles(list:FileList|null,asLogo=false){if(!list?.length)return;const incoming=Array.from(list);if(incoming.some(f=>f.size>10*1024*1024)){setError('Каждый файл должен быть не больше 10 МБ.');return;}if(asLogo){setLogo(incoming[0]);setColors([]);}else if(files.length+incoming.length>10)setError('До 10 материалов за одну загрузку.');else setFiles([...files,...incoming]);}
 async function extractColors(){if(!logoUrl)return;try{const image=new Image();image.src=logoUrl;await image.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.drawImage(image,0,0,64,64);const pixels=ctx.getImageData(0,0,64,64).data,counts=new Map<string,number>();for(let i=0;i<pixels.length;i+=4){const rgb=[pixels[i],pixels[i+1],pixels[i+2]];if(pixels[i+3]<180||Math.max(...rgb)-Math.min(...rgb)<28)continue;const key='#'+rgb.map(v=>Math.min(255,Math.round(v/32)*32).toString(16).padStart(2,'0').slice(-2)).join('');counts.set(key,(counts.get(key)||0)+1);}const picked=[...counts].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([color])=>color);setColors(picked);if(picked.length)setProfile(p=>({...p,palette:{...p.palette,primary:picked[0],accent:picked[1]||picked[0]}}));else setError('Логотип нейтральный. Выберите цвета вручную.');}catch{setError('Не удалось прочитать цвета логотипа. Выберите их вручную.');}}
 async function persist(){
  if(!profile.name.trim())throw new Error('Укажите название партнёра.');
  if(!brandId.current){const created=await api('/brands',{name:profile.name.trim(),primary:profile.palette.primary});brandId.current=created.id;}
  const id=brandId.current!,next={...profile,brandId:id,name:profile.name.trim(),status:'confirmed' as const};let uploaded=[...assets];
  for(const [role,pending] of [['logo',logo?[logo]:[]],['style',files]] as const){if(!pending.length)continue;const form=new FormData();for(const file of pending)form.append('files',file);form.append('role',role);form.append('pages','1,2,3');const result=await uploadAssets(id,form);uploaded=[...uploaded,...result.assets];setAssets(uploaded);if(role==='logo'){next.logoAssetId=result.assets.find((a:any)=>a.mime.startsWith('image/'))?.id||null;setLogo(null);setLogoUrl(result.assets[0]?.url||'');}else setFiles([]);}
  next.logoAssetId=next.logoAssetId||uploaded.find(a=>a.role==='logo')?.id||null;
  next.sourceAssets=[...new Set([...next.sourceAssets,...uploaded.filter(a=>a.mime.startsWith('image/')).map(a=>a.id)])];
  const saved=await api<BrandProfile>('/brands/'+id+'/versions',next);setProfile(saved);const brand=await api('/brands/'+id);await refreshBrands();return brand;
 }
 async function save(){if(pending.current||job)return;pending.current=true;setSaving(true);setError('');try{const b=await persist();onSaved(brandChoice(b,b.profile,b.assets));}catch(e){if(live.current)setError((e as Error).message);}finally{pending.current=false;if(live.current)setSaving(false);}}
 async function analyze(){if(pending.current||job)return;pending.current=true;setSaving(true);setError('');try{const b=await persist();const response=await api('/brands/'+b.id+'/analyses',{brandId:b.id,prompt:'Изучи фирменный стиль партнёра по логотипу и материалам: цвета, шрифт заголовков, тон и изображения',referenceAssetIds:b.profile.sourceAssets.slice(0,10),brandVersion:b.version,draftRevision:0,count:1,quality:'medium',format:'full',strictness:'strict'},'POST',crypto.randomUUID());activeJob.current=response.jobId;if(!live.current){await api('/jobs/'+response.jobId+'/cancel',{});return;}setJob(response.jobId);}catch(e){if(live.current)setError((e as Error).message);}finally{pending.current=false;if(live.current)setSaving(false);}}
 const busy=saving||!!job,preview={...defaultDesign,brandId:'partner-draft',asset:'/assets/brand-neutral.svg',logo:logoUrl||undefined,brandTokens:{name:profile.name||'Партнёр',primary:profile.palette.primary,ink:profile.palette.onPrimary,paper:profile.palette.canvas,font:profile.typography.display.family||'Inter',pattern:''}};
 return <Modal wide className="partner-style-modal" title="Настроить стиль партнёра" onClose={()=>{if(!saving)onClose();}}><div className="partner-modal-layout"><fieldset disabled={busy} className="partner-modal-fields">
  <p>Цвета, шрифт и логотип будут использоваться в купонах этого партнёра.</p>
  <Field label="Название партнёра"><input autoFocus maxLength={80} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></Field>
  <div className="field"><span>Логотип</span><label className="button"><ImagePlus size={16}/>Загрузить логотип<input hidden type="file" accept=".png,.jpg,.jpeg,.webp,.svg" onChange={e=>addFiles(e.target.files,true)}/></label></div>
  {logoUrl&&<div className="row"><img className="partner-logo-thumb" src={assetURL(logoUrl)} alt="Логотип партнёра"/><Button onClick={()=>void extractColors()}>Взять цвета из логотипа</Button><Button aria-label="Убрать выбранный логотип" onClick={()=>{setLogo(null);setLogoUrl('');setAssets(assets.filter(a=>a.role!=='logo'));setProfile({...profile,logoAssetId:null,sourceAssets:profile.sourceAssets.filter(id=>!assets.some(a=>a.id===id&&a.role==='logo'))});}}><X size={16}/></Button></div>}
  {!!colors.length&&<div className="palette-swatches">{colors.map(c=><button key={c} aria-label={'Основной цвет '+c} style={{background:c,width:28,height:28,borderRadius:'50%'}} onClick={()=>setProfile({...profile,palette:{...profile.palette,primary:c}})}/>)}</div>}
  <div className="form-grid">{paletteFields.map(([key,label])=><Field key={key} label={label}><div className="color-field"><input type="color" value={profile.palette[key]} onChange={e=>setProfile({...profile,palette:{...profile.palette,[key]:e.target.value}})}/><span>{profile.palette[key]}</span></div></Field>)}</div>
  <Field label="Шрифт заголовков"><select value={profile.typography.display.family||'Inter'} onChange={e=>setProfile({...profile,typography:{...profile.typography,display:{...profile.typography.display,family:e.target.value,assetId:null,origin:'provided'}}})}>{[...new Set(['Inter','Georgia','Arial','Prata',profile.typography.display.family].filter(Boolean))].map(font=><option key={font}>{font}</option>)}</select></Field>
  <Field label="Тон общения"><textarea maxLength={1000} value={profile.toneOfVoice} onChange={e=>setProfile({...profile,toneOfVoice:e.target.value})}/></Field>
  <Field label="Коротко о фирменном стиле"><textarea rows={3} maxLength={2000} value={profile.imagery.description} onChange={e=>setProfile({...profile,imagery:{...profile.imagery,description:e.target.value}})}/></Field>
  <div className="field"><span>Материалы стиля</span><label className="button"><Upload size={16}/>Добавить материалы<input hidden type="file" multiple accept=".png,.jpg,.jpeg,.webp,.svg,.pdf,.woff,.woff2,.ttf,.otf" onChange={e=>addFiles(e.target.files)}/></label></div>
  {files.map((f,i)=><div className="split" key={f.name+i}><span>{f.name}</span><Button aria-label={'Убрать '+f.name} onClick={()=>setFiles(files.filter((_,index)=>index!==i))}><X size={14}/></Button></div>)}{assets.length>0&&<small>Сохранено материалов: {assets.length}. Полная библиотека доступна в настройке стиля.</small>}
 </fieldset><aside className="partner-modal-preview"><small>ОБРАЗЕЦ КУПОНА</small><div inert><CouponRenderer design={preview} offer={defaultOffer} format="list"/></div><p>Образец меняется по ходу настройки.</p></aside></div>
 <div className="partner-ai-assembly"><Button disabled={busy||!status?.analysisConnected||!(logo||files.length||assets.length)||!profile.name.trim()} onClick={()=>void analyze()}><Sparkles size={16}/>{job?'Изучаем материалы…':'Собрать стиль с помощью ИИ'}</Button>{job&&<Button onClick={()=>void api('/jobs/'+job+'/cancel',{}).catch(e=>setError(e.message))}>Остановить</Button>}<small>{status?.analysisConnected?'ИИ предложит настройки по сохранённым материалам. Результат можно отредактировать.':'Стиль можно настроить вручную. Для анализа подключите ИИ в настройках.'}</small></div>
 {error&&<p role="alert" className="error-box">{error}</p>}<div className="modal-actions"><Button disabled={saving} onClick={onClose}>Отмена</Button><Button primary disabled={busy||!profile.name.trim()} onClick={()=>void save()}>{saving?'Сохраняем…':'Сохранить стиль'}</Button></div></Modal>;
}
