import {useMemo} from 'react';
import {useNavigate} from 'react-router-dom';
import {Banknote,ArrowRight} from 'lucide-react';
import {useStore} from './store';
import {stores,num,type Campaign,type Customer} from './domain';
import {Button,Field} from './ui';
import {defaultPaymentPolicy,paymentLabels,paymentProfile,paymentAudience,type PreferredPayment} from './paymentTargeting';

export function PaymentPreferences(){
 const state=useStore(),navigate=useNavigate();
 const profiles=useMemo(()=>{const map=new Map(stores.map(s=>[s.id,[] as NonNullable<typeof state.data>['receipts']]));for(const r of state.data?.receipts||[])map.get(r.storeId)?.push(r);return new Map(stores.map(s=>[s.id,paymentProfile(map.get(s.id)!,'2026-09-14',90)]));},[state.data]);
 return <><section className="panel pm-payment-intro"><Banknote size={28}/><div><h2>Нужная оплата — через подходящую аудиторию</h2><p>Укажите приоритет каждой точки. В купоне включите подбор по истории: предложение получат клиенты, которые чаще выбирают этот способ. Скидка действует при любой оплате.</p></div></section><p className="pm-source-note">История до 14.09.2026 · последние 90 дней. В демо способы оплаты синтетические. После импорта считаются только явно указанные способы; смешанная и неизвестная оплата не угадываются.</p><div className="pm-payment-grid">{stores.map(s=>{const p=profiles.get(s.id)!;return <section className="panel pm-payment-card" key={s.id}><div className="split"><h3>{s.name}</h3><span className="badge">{num(p.total)} чеков</span></div><div className="pm-payment-bars">{(['cash','card','sbp'] as const).map(method=><div key={method}><span>{paymentLabels[method]}</span><div className="bar"><i style={{width:(p.known?p.counts[method]/p.known*100:0)+'%'}}/></div><b>{p.known?num(p.counts[method]/p.known*100)+'%':'—'}</b></div>)}</div><small>Способ известен у {num(p.coverage*100)}% чеков</small><Field label="Что сейчас важно точке"><select value={state.paymentNeeds[s.id]||''} onChange={e=>{const needs={...state.paymentNeeds};if(e.target.value)needs[s.id]=e.target.value as PreferredPayment;else delete needs[s.id];useStore.setState({paymentNeeds:needs});}}><option value="">Без предпочтения</option><option value="cash">Больше наличных</option><option value="card">Больше оплат картой</option><option value="sbp">Больше оплат через СБП</option></select></Field></section>;})}</div><div className="pm-bottom-action"><Button primary onClick={()=>navigate('/campaigns/new')}>Создать купон с подбором аудитории<ArrowRight size={17}/></Button></div></>;
}

export function PaymentAudienceSettings({campaign,customers,disabled,onChange}:{campaign:Campaign;customers:Customer[];disabled:boolean;onChange:(patch:Partial<Campaign>)=>void}){
 const state=useStore(),navigate=useNavigate(),policy=campaign.paymentPolicy||defaultPaymentPolicy;
 const needs=campaign.paymentNeedsSnapshot||state.paymentNeeds;
 const result=paymentAudience(customers,needs,policy,'2026-09-14');
 return <section className="pm-targeting"><label className="pm-toggle"><input type="checkbox" disabled={disabled} checked={policy.enabled} onChange={e=>onChange({paymentPolicy:{...policy,enabled:e.target.checked}})}/><span><b>Учитывать привычный способ оплаты</b><small>Подбирать аудиторию под приоритет магазина</small></span></label>{policy.enabled&&<><div className="form-grid"><Field label="История"><select value={policy.window} disabled={disabled} onChange={e=>onChange({paymentPolicy:{...policy,window:Number(e.target.value)}})}>{[30,60,90,120].map(n=><option key={n} value={n}>{n} дней</option>)}</select></Field><Field label="Минимальная доля способа, %"><input type="number" min={51} max={100} disabled={disabled} value={policy.minShare} onChange={e=>onChange({paymentPolicy:{...policy,minShare:Number(e.target.value)}})}/></Field><Field label="Минимум чеков с известной оплатой"><input type="number" min={3} max={50} disabled={disabled} value={policy.minKnown} onChange={e=>onChange({paymentPolicy:{...policy,minKnown:Number(e.target.value)}})}/></Field></div><p className="pm-targeting-result"><b>{num(result.eligible.length)}</b> подходят по привычке оплаты</p><div className="pm-targeting-reasons"><span>Недостаточно истории: {num(result.excluded.unknown)}</span><span>Другой способ / нет явного предпочтения: {num(result.excluded.other)}</span><span>У точки нет приоритета: {num(result.excluded.noNeed)}</span></div><p>Известный способ нужен минимум у 60% чеков клиента. Контрольная группа выбирается из той же аудитории. При назначении приоритеты сохраняются вместе с кампанией.</p><Button onClick={()=>navigate('/payments')}>Настроить приоритеты точек<ArrowRight size={15}/></Button></>}<small>Рекомендация для отбора аудитории, а не обязательное условие оплаты купона.</small></section>;
}
