import {useState} from 'react';
import {get,set} from 'idb-keyval';
import Papa from 'papaparse';
import {useStore} from './store';
import type {Customer} from './domain';
import {Button,download} from './ui';
export const profileColumns=['customer_id','gender','birth_date','customer_type','loyalty_level','joined_on','points_to_next','coins','redeemed_coins','referred','referrals','played','survey','consent','channel'];
export function parseProfiles(text:string,customers:Customer[]){
 const parsed=Papa.parse<Record<string,string>>(text,{header:true,skipEmptyLines:true}),errors=parsed.errors.map(e=>e.message),rows:Customer[]=[],known=new Map(customers.map(c=>[c.id,c])),seen=new Set<string>();
 if(!parsed.meta.fields?.includes('customer_id'))return {rows,errors:['Нужен столбец customer_id']};
 parsed.data.forEach((r,i)=>{try{const id=r.customer_id?.trim(),base=known.get(id);if(!base)throw Error('Покупатель не найден в текущем наборе');if(seen.has(id))throw Error('Повторный customer_id');seen.add(id);
  const choice=(value:string|undefined,allowed:string[])=>{if(!value?.trim())return undefined;if(!allowed.includes(value.trim()))throw Error('Неизвестное значение '+value);return value.trim();};
  const bool=(v:string|undefined)=>v?.trim()?choice(v,['true','false','1','0'])==='true'||v==='1':undefined;
  const number=(v:string|undefined)=>{if(!v?.trim())return undefined;const n=Number(v);if(!Number.isSafeInteger(n)||n<0)throw Error('Ожидается неотрицательное целое');return n;};
  const date=(v:string|undefined)=>{if(!v?.trim())return undefined;if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T12:00Z'))||new Date(v+'T12:00Z').toISOString().slice(0,10)!==v||v>'2026-09-14')throw Error('Проверьте дату');return v;};
  rows.push({...base,birthDate:date(r.birth_date)||null,consent:bool(r.consent)??false,channel:bool(r.channel)??false,loyalty:{gender:choice(r.gender,['female','male','unknown']),type:choice(r.customer_type,['new','regular']),level:choice(r.loyalty_level,['base','silver','gold']),joinedOn:date(r.joined_on),pointsToNext:number(r.points_to_next),coins:number(r.coins),redeemedCoins:bool(r.redeemed_coins),referred:bool(r.referred),referrals:number(r.referrals),played:bool(r.played),survey:bool(r.survey)}});
 }catch(e){errors.push(`Строка ${i+2}: ${(e as Error).message}`);}});return {rows,errors};
}
export function ProfileImport(){const data=useStore(s=>s.data)!,[preview,setPreview]=useState<ReturnType<typeof parseProfiles>|null>(null),[error,setError]=useState('');return <section className="panel section-gap"><div className="split"><div><h2>Профили для точного отбора</h2><p>Пол, дата рождения, карта, монеты, приглашения и согласия. Пустые значения остаются неизвестными.</p></div><Button onClick={()=>download('customer-profiles.csv','\uFEFF'+profileColumns.join(',')+'\r\n00001,female,1990-06-20,regular,silver,2026-01-01,150,40,true,false,0,false,true,true,true\r\n','text/csv')}>Шаблон профилей</Button></div><label className="button section-gap">Загрузить CSV профилей<input hidden type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setError('');if(f.size>10*1024*1024){setError('Максимум 10 МБ');return;}try{setPreview(parseProfiles(await f.text(),data.customers));}catch(err){setError((err as Error).message);}}}/></label>{error&&<p role="alert" className="error-box">{error}</p>}{preview&&<div className="section-gap"><p>Профилей: {preview.rows.length}. Ошибок: {preview.errors.length}.</p>{preview.errors.slice(0,8).map(e=><p key={e} className="negative">{e}</p>)}<Button primary disabled={!preview.rows.length||!!preview.errors.length} onClick={async()=>{try{const updates=preview.rows.map(({receipts,...c})=>c);const previous=await get<any[]>('srez-customer-profiles-v1')||[];const merged=new Map(previous.map(p=>[p.id,p]));updates.forEach(p=>merged.set(p.id,p));await set('srez-customer-profiles-v1',[...merged.values()]);const byId=new Map(preview.rows.map(c=>[c.id,c]));useStore.setState({data:{...data,customers:data.customers.map(c=>byId.get(c.id)||c)}});setPreview(null);useStore.getState().notify('Профили загружены');}catch{setError('Не удалось сохранить профили');}}}>Подтвердить импорт профилей</Button></div>}</section>;}
