import {create} from 'zustand';
import {isPages} from './runtime';
import {persist} from 'zustand/middleware';
import {get,set} from 'idb-keyval';
import {campaignsSeed,baseSegment,type Dataset,type Campaign,type Group,type Redemption,type Receipt} from './domain';
export interface Segment {id:string;name:string;rules:Group}
interface State {data:Dataset|null;progress:number;campaigns:Campaign[];segments:Segment[];events:Redemption[];returns:Receipt[];simulationDate:string;logs:{id:string;campaign:string;text:string;at:string}[];settings:{name:string;motion:string;role:string;store:string;scenario:string;dataset:string};chat:{question:string;answer:string;link:string;context:string}[];toast:string;setData:(d:Dataset)=>void;updateCampaign:(id:string,patch:Partial<Campaign>,log?:string)=>void;addCampaign:(c:Campaign)=>void;saveSegment:(s:Segment)=>void;notify:(s:string)=>void;resetSimulation:()=>void;}
export const useStore=create<State>()(persist((setState,getState)=>({data:null,progress:0,campaigns:campaignsSeed(),segments:[{id:'weekend',name:'Приходят по выходным',rules:baseSegment},{id:'lost',name:'Давно не были',rules:{id:'lost-root',logic:'AND',children:[{id:'lost-1',field:'last',op:'gte',value:30,window:120}]}},{id:'snacks',name:'Покупают снеки',rules:{id:'snack-root',logic:'AND',children:[{id:'snack-1',field:'category',op:'yes',value:2,window:60}]}}],events:[],returns:[],simulationDate:'2026-09-14T10:00',logs:[],settings:{name:'Квартал 12',motion:'system',role:'owner',store:'',scenario:'full',dataset:'seed'},chat:[],toast:'',setData:data=>setState({data}),updateCampaign:(id,patch,log)=>setState(s=>({campaigns:s.campaigns.map(c=>c.id===id?{...c,...patch}:c),logs:log?[{id:crypto.randomUUID(),campaign:id,text:log,at:new Date().toISOString()},...s.logs].slice(0,80):s.logs})),addCampaign:c=>setState(s=>({campaigns:[c,...s.campaigns],logs:[{id:crypto.randomUUID(),campaign:c.id,text:'Создан черновик',at:new Date().toISOString()},...s.logs]})),saveSegment:segment=>setState(s=>({segments:s.segments.some(x=>x.id===segment.id)?s.segments.map(x=>x.id===segment.id?segment:x):[...s.segments,segment]})),notify:toast=>{setState({toast});setTimeout(()=>{if(getState().toast===toast)setState({toast:''});},4200);},resetSimulation:()=>setState(s=>({events:[],returns:[],simulationDate:'2026-09-14T10:00',campaigns:s.campaigns.map(c=>c.id==='CP-097'?c:{...c,status:'draft',assignments:[],snapshot:undefined})}))}),{name:'srez-workspace-v1',version:1,partialize:s=>({campaigns:s.campaigns,segments:s.segments,events:s.events,returns:s.returns,simulationDate:s.simulationDate,logs:s.logs,settings:s.settings,chat:s.chat}),migrate:()=>({campaigns:campaignsSeed()}) as State}));
let loading:Promise<void>|undefined;
export function loadData(){if(loading)return loading;loading=(async()=>{const saved=await get<Dataset>('srez-seed-v1');if(saved?.schemaVersion===2){useStore.setState({data:saved,progress:100});return;}await new Promise<void>((resolve,reject)=>{const worker=new Worker(new URL('./seed.worker.ts',import.meta.url),{type:'module'});worker.onmessage=async({data})=>{if(data.data){await set('srez-seed-v1',data.data);useStore.setState({data:data.data,progress:100});worker.terminate();resolve();}else useStore.setState({progress:data.progress});};worker.onerror=reject;worker.postMessage({start:true});});})();return loading;}
export async function api<T=any>(url:string,body?:unknown,method='POST',key?:string):Promise<T>{if(isPages)return (await import('./pagesStore')).pagesStore.request(url,body);const r=await fetch('/api'+url,body===undefined?undefined:{method,headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw new Error(v.error||'Не удалось выполнить действие');return v;}
